(self.AMP=self.AMP||[]).push({n:"amp-bind",v:"1908231648370",f:(function(AMP,_){
var l,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={a:!0},ea={};try{ea.__proto__=da;ca=ea.a;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var fa=ba;
function ha(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(fa)fa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.La=b.prototype}var ia=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a}(this);function ja(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var ka=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function q(a){var b=Object.create(null);if(!a)return b;for(var c;c=ka.exec(a);){var d=ja(c[1],c[1]),e=c[2]?ja(c[2],c[2]):"";b[d]=e}return b};var la="";
function t(){var a,b=a||self;if(b.__AMP_MODE)var c=b.__AMP_MODE;else{c=b;var d=self.AMP_CONFIG||{},e=!!d.test||!1,f=c.__karma__&&c.__karma__.config.amp.testOnIe,g=q(c.location.originalHash||c.location.hash);d=d.spt;var h=q(c.location.search);la||(la=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"011908231648370");c={localDev:!1,development:!(!["1","actions","amp","amp4ads","amp4email"].includes(g.development)&&!c.AMP_DEV_MODE),examiner:"2"==g.development,filter:g.filter,geoOverride:g["amp-geo"],userLocationOverride:g["amp-user-location"],
minified:!0,lite:void 0!=h.amp_lite,test:e,testIe:f,log:g.log,version:"1908231648370",rtvVersion:la,singlePassType:d};c=b.__AMP_MODE=c}return c};var ma=Object.prototype.toString;function u(a){return a?Array.prototype.slice.call(a):[]}function na(a){return"[object Object]"===ma.call(a)};var v=self.AMP_CONFIG||{},w={thirdParty:v.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:v.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof v.thirdPartyFrameRegex?new RegExp(v.thirdPartyFrameRegex):v.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:v.cdnUrl||"https://cdn.ampproject.org",cdnProxyRegex:("string"==typeof v.cdnProxyRegex?new RegExp(v.cdnProxyRegex):v.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,
errorReporting:v.errorReportingUrl||"https://amp-error-reporting.appspot.com/r",localDev:v.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.dev$/]};function oa(a){var b=Object.getOwnPropertyDescriptor(a,"message");if(b&&b.writable)return a;var c=a.stack,d=Error(a.message),e;for(e in a)d[e]=a[e];d.stack=c;return d}self.log=self.log||{user:null,dev:null,userForEmbed:null};var x=self.log;function y(){if(!x.user)throw Error("failed to call initLogConstructor");return x.user}function A(){if(x.dev)return x.dev;throw Error("failed to call initLogConstructor");}
function B(a,b,c,d,e){return y().assert(a,b,c,d,e,void 0,void 0,void 0,void 0,void 0,void 0)};var pa=Object.prototype.hasOwnProperty;function C(a){var b=Object.create(null);a&&Object.assign(b,a);return b}function D(a){return a||{}}function E(a,b){if(pa.call(a,b))return a[b]}
function qa(a,b){var c=10;c=void 0===c?10:c;var d=[],e=[];e.push({t:a,s:b,d:0});for(a={};0<e.length;){b=e.shift();a.G=b.t;a.B=b.s;a.P=b.d;if(d.includes(a.B))throw Error("Source object has a circular reference.");d.push(a.B);a.G!==a.B&&(a.P>c?Object.assign(a.G,a.B):Object.keys(a.B).forEach(function(a){return function(b){var c=a.B[b];if(pa.call(a.G,b)){var d=a.G[b];if(na(c)&&na(d)){e.push({t:d,s:c,d:a.P+1});return}}a.G[b]=c}}(a)));a={B:a.B,G:a.G,P:a.P}}};function F(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var G,ra="Webkit webkit Moz moz ms O o".split(" ");function sa(a){var b=!1;void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function ta(){return AMP.BaseElement.apply(this,arguments)||this}ha(ta,AMP.BaseElement);l=ta.prototype;l.getLayoutPriority=function(){return 1};l.isAlwaysFixed=function(){return!0};l.isLayoutSupported=function(){return!0};l.renderOutsideViewport=function(){return!0};l.S=function(){return"<amp-bind-macro> "+(this.element.getAttribute("id")||"<unknown id>")};function J(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};function K(){var a=100;this.ta=a;this.X=this.ba=0;this.R=Object.create(null)}K.prototype.has=function(a){return!!this.R[a]};K.prototype.get=function(a){var b=this.R[a];if(b)return b.access=++this.X,b.payload};K.prototype.put=function(a,b){this.has(a)||this.ba++;this.R[a]={payload:b,access:this.X};if(!(this.ba<=this.ta)){A().warn("lru-cache","Trimming LRU cache");a=this.R;var c=this.X+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.ba--)}};var ua=D({c:!0,v:!0,a:!0,ad:!0,action:!0}),va,wa,xa=/[?&]amp_js[^&]*/,ya=/[?&]amp_gsa[^&]*/,za=/[?&]amp_r[^&]*/,Aa=/[?&]amp_kit[^&]*/,Ba=/[?&]usqp[^&]*/;
function L(a){var b;va||(va=self.document.createElement("a"),wa=self.UrlCache||(self.UrlCache=new K));var c=b?null:wa,d=va;if(c&&c.has(a))a=c.get(a);else{d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=
d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;c&&c.put(a,e);a=e}return a}
function Ca(a,b){var c=void 0===c?"source":c;B(null!=a,"%s %s must be available",b,c);var d=a;a=d;"string"==typeof a&&(a=L(a));var e;(e="https:"==a.protocol||"localhost"==a.hostname||"127.0.0.1"==a.hostname)||(a=a.hostname,e=a.length-10,e=0<=e&&a.indexOf(".localhost",e)==e);B(e||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d)}
function M(a){"string"==typeof a&&(a=L(a));return w.cdnProxyRegex.test(a.origin)}
function Da(a){"string"==typeof a&&(a=L(a));if(!M(a))return a.href;var b=a.pathname.split("/");B(ua[b[1]],"Unknown path prefix in url %s",a.href);var c=b[2],d="s"==c?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(c);B(0<d.indexOf("."),"Expected a . in origin %s",d);b.splice(1,"s"==c?3:2);b=d+b.join("/");d=(d=a.search)&&"?"!=d?(d=d.replace(xa,"").replace(ya,"").replace(za,"").replace(Aa,"").replace(Ba,"").replace(/^[?&]/,""))?"?"+d:"":"";return b+d+(a.hash||"")}
function Ea(a,b){"string"==typeof b&&(b=L(b));if("function"==typeof URL)var c=(new URL(a,b.href)).toString();else{c=a;var d=b;"string"==typeof d&&(d=L(d));c=c.replace(/\\/g,"/");var e=L(c);c=F(c.toLowerCase(),e.protocol)?e.href:F(c,"//")?d.protocol+c:F(c,"/")?d.origin+c:d.origin+d.pathname.replace(/\/[^/]*$/,"/")+c}return c}function Fa(a){var b=L(a),c=q(b.search);B(!("__amp_source_origin"in c),"Source origin is not allowed in %s",a)};function Ga(a,b){if(a.__AMP__EXPERIMENT_TOGGLES)var c=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);c=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var d in a.AMP_CONFIG){var e=a.AMP_CONFIG[d];"number"===typeof e&&0<=e&&1>=e&&(c[d]=Math.random()<e)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(d=a.AMP_CONFIG["allow-doc-opt-in"],e=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){e=
e.getAttribute("content").split(",");for(var f=0;f<e.length;f++)-1!=d.indexOf(e[f])&&(c[e[f]]=!0)}Object.assign(c,Ja(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length)for(d=a.AMP_CONFIG["allow-url-opt-in"],a=q(a.location.originalHash||a.location.hash),e=0;e<d.length;e++)f=a["e-"+d[e]],"1"==f&&(c[d[e]]=!0),"0"==f&&(c[d[e]]=!1)}var g=c;return!!g[b]}
function Ja(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(e){A().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var d=0;d<c.length;d++)0!=c[d].length&&("-"==c[d][0]?a[c[d].substr(1)]=!1:a[c[d]]=!0);return a};function Ka(a,b){var c=a.ownerDocument.defaultView,d=N(c),e=c!=d,f=Ga(d,"ampdoc-fie");e&&!f?b=La(c,b)?O(c,b):null:(a=P(a),a=Q(a),b=La(a,b)?O(a,b):null);return b}function Ma(a,b){var c=N(a);La(a,"bind");if(Ga(c,"ampdoc-fie")){var d=P(a.document);Na(Q(d),d,"bind",function(){return b},!0)}else Na(a,a,"bind",function(){return b}),O(a,"bind")}function R(a,b){a=N(a);return O(a,b)}function T(a,b){var c=P(a);c=Q(c);return O(c,b)}function Oa(a,b){return Pa(Q(a),b)}
function N(a){return a.__AMP_TOP||(a.__AMP_TOP=a)}function P(a){return a.nodeType?R((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function Q(a){a=P(a);return a.isSingleDoc()?a.win:a}function O(a,b){La(a,b);var c=Qa(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}
function Na(a,b,c,d,e){var f=Qa(a),g=f[c];g||(g=f[c]={obj:null,promise:null,resolve:null,reject:null,context:null,ctor:null});if(e||!g.ctor&&!g.obj)g.ctor=d,g.context=b,g.resolve&&O(a,c)}function Ra(a,b){var c=Pa(a,b);if(c)return c;a=Qa(a);a[b]=Sa();return a[b].promise}function Pa(a,b){var c=Qa(a)[b];if(c){if(c.promise)return c.promise;O(a,b);return c.promise=Promise.resolve(c.obj)}return null}function Qa(a){var b=a.services;b||(b=a.services={});return b}
function La(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)}function Sa(){var a=new J,b=a,c=b.promise,d=b.resolve;b=b.reject;c.catch(function(){});return{obj:null,promise:c,resolve:d,reject:b,context:null,ctor:null}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function Ta(a,b,c){if(b(a))c();else{var d=a.ownerDocument.defaultView;if(d.MutationObserver){var e=new d.MutationObserver(function(){b(a)&&(e.disconnect(),c())});e.observe(a,{childList:!0})}else var f=d.setInterval(function(){b(a)&&(d.clearInterval(f),c())},5)}}function Ua(a,b){Ta(a.documentElement,function(){return!!a.body},b)}function Va(a){return new Promise(function(b){return Ua(a,b)})}function Wa(a,b){for(var c;a&&a!==c;a=a.parentElement)if(b(a))return a;return null}
function Xa(a,b){return a.closest?a.closest(b):Wa(a,function(a){var c=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return c?c.call(a,b):!1})}function Ya(a,b){for(var c=a.length,d=0;d<c;d++)b(a[d],d)}function Za(a){return"SCRIPT"==a.tagName&&a.hasAttribute("type")&&"APPLICATION/JSON"==a.getAttribute("type").toUpperCase()}
function $a(a){F(a.tagName,"AMP-");if(a.createdCallback)return Promise.resolve(a);if(!a.__AMP_UPG_PRM){var b=new J;a.__AMP_UPG_PRM=b.promise;a.__AMP_UPG_RES=b.resolve}return a.__AMP_UPG_PRM};function ab(a,b,c){var d=Oa(a,b);if(d)return d;var e=P(a);return e.waitForBodyOpen().then(function(){return bb(e.win,c,e.win.document.head)}).then(function(){var d=e.win;return d.__AMP_EXTENDED_ELEMENTS&&d.__AMP_EXTENDED_ELEMENTS[c]?Ra(Q(a),b):null})}function cb(a){var b=Ka(a,"bind");if(b)return Promise.resolve(b);b=a.ownerDocument.defaultView;var c=N(b);return b!==c?db(b):ab(a,"bind","amp-bind")}
function bb(a,b,c){if(c){var d=[];c=c.querySelectorAll("script[custom-element]");for(var e=0;e<c.length;e++)d.push(c[e].getAttribute("custom-element"))}else d=[];if(!d.includes(b))return Promise.resolve();var f=R(a,"extensions");return f.waitForExtension(a,b)}function db(a){return Va(a.document).then(function(){return bb(a,"amp-bind",a.document.head)}).then(function(){return a.__AMP_EXTENDED_ELEMENTS&&a.__AMP_EXTENDED_ELEMENTS["amp-bind"]?Ra(a,"bind"):null})};function eb(a,b){if("."==b)return a;b=b.split(".");for(var c=0;c<b.length;c++){var d=b[c];if(d&&a&&void 0!==a[d]&&(null==a||"object"!=typeof a?0:Object.prototype.hasOwnProperty.call(a,d)))a=a[d];else{a=void 0;break}}return a}function fb(a,b){try{return JSON.parse(a)}catch(c){return b&&b(c),null}}
function gb(a,b){var c=10;c=void 0===c?5:c;if(!isFinite(c)||0>c)throw Error("Invalid depth: "+c);if(a===b)return!0;for(a=[{a:a,b:b,depth:c}];0<a.length;){var d=a.shift();b=d.a;c=d.b;d=d.depth;if(0<d){if(typeof b!==typeof c)return!1;if(Array.isArray(b)&&Array.isArray(c)){if(b.length!==c.length)return!1;for(var e=0;e<b.length;e++)a.push({a:b[e],b:c[e],depth:d-1});continue}else if(b&&c&&"object"===typeof b&&"object"===typeof c){var f=Object.keys(b),g=Object.keys(c);if(f.length!==g.length)return!1;for(e=
0;e<f.length;e++){var h=f[e];a.push({a:b[h],b:c[h],depth:d-1})}continue}}if(b!==c)return!1}return!0};function hb(a,b,c,d,e){var f=void 0;f=void 0===f?".":f;c=void 0===c?0:c;d=void 0===d?!1:d;Ca(b.getAttribute("src"),b);var g=R(a.win,"batched-xhr");return ib(b,c,d).then(function(a){void 0!==e&&(a.fetchOpt.method="POST",a.fetchOpt.headers={"Content-Type":"application/x-www-form-urlencoded"},a.fetchOpt.body={ampViewerAuthToken:e});return g.fetchJson(a.xhrUrl,a.fetchOpt)}).then(function(a){return a.json()}).then(function(a){if(null==a)throw Error("Response is undefined.");return eb(a,f||".")})}
function ib(a,b,c){var d=a.getAttribute("src"),e=Ka(a,"url-replace");return(1<=b?e.expandUrlAsync(d):Promise.resolve(d)).then(function(d){if(1==b){var f=e.collectUnwhitelistedVarsSync(a);if(0<f.length)throw y().createError('URL variable substitutions in CORS fetches from dynamic URLs (e.g. via amp-bind) require opt-in. Please add data-amp-replace="'+(f.join(" ")+'" to the <')+(a.tagName+"> element. See https://bit.ly/amp-var-subs."));}var h={};a.hasAttribute("credentials")&&(h.credentials=a.getAttribute("credentials"));
c&&(h.cache="reload");return{xhrUrl:d,fetchOpt:h}})};function jb(a,b,c,d){var e={detail:c};Object.assign(e,d);if("function"==typeof a.CustomEvent)return new a.CustomEvent(b,e);a=a.document.createEvent("CustomEvent");a.initCustomEvent(b,!!e.bubbles,!!e.cancelable,c);return a};function kb(a,b){for(var c=[],d=0,e=0;e<a.length;e++){var f=a[e];b(f,e,a)?c.push(f):(d<e&&(a[d]=f),d++)}d<a.length&&(a.length=d)}function lb(a,b){for(var c=0;c<a.length;c++)if(b(a[c],c,a))return c;return-1};function mb(a){var b=a.getAttribute("crossorigin");return b&&"amp-viewer-auth-token-via-post"===b.trim()?ab(a,"amp-viewer-assistance","amp-viewer-assistance").then(function(a){B(a,'crossorigin="amp-viewer-auth-token-post" requires amp-viewer-assistance extension.');return a.getIdTokenPromise()}).then(function(a){return a||""}).catch(function(){return""}):Promise.resolve(void 0)};function nb(a){a=AMP.BaseElement.call(this,a)||this;a.T=void 0;return a}ha(nb,AMP.BaseElement);l=nb.prototype;l.getLayoutPriority=function(){return 1};l.isAlwaysFixed=function(){return!0};l.isLayoutSupported=function(){return!0};
l.buildCallback=function(){var a=this;sa(this.element);this.element.setAttribute("aria-hidden","true");var b=this.element;b.hasAttribute("overridable")&&cb(b).then(function(a){a.addOverridableKey(b.getAttribute("id"))});this.parseAndUpdate();this.element.hasAttribute("src")&&ob(this,!0);this.registerAction("refresh",function(){B(a.element.hasAttribute("src"),'Can\'t refresh <amp-state> without "src" attribute.');ob(a,!1,!0)},100)};
l.mutatedAttributesCallback=function(a){if(T(this.element,"viewer").hasBeenVisible())void 0!==a.src&&ob(this,!1);else{var b=this.S();A().error(b,"Viewer must be visible before mutation.")}};l.renderOutsideViewport=function(){return!0};l.parseAndUpdate=function(){return void 0===this.T&&(this.T=pb(this),null!==this.T)?qb(this,this.T,!0):Promise.resolve()};
function pb(a){var b=a.element.children;if(0==b.length)return null;var c=a.S();if(1!=b.length)return a.user().error(c,"Should contain exactly one <script> child."),null;var d=b[0];return Za(d)?fb(d.textContent,function(b){a.user().error(c,"Failed to parse state. Is it valid JSON?",b)}):(a.user().error(c,'State should be in a <script> tag with type="application/json".'),null)}
function vb(a,b,c){var d=a.element,e=a.getAmpDoc(),f=d.getAttribute("src"),g=L(Da(f)).origin!==L(Da(e.win.location)).origin,h=g&&!b?1:2;return mb(d).then(function(b){return hb(e,a.element,h,c,b).catch(function(b){b=b?jb(a.win,"amp-state.error",D({response:b.response})):null;var c=Ka(d,"action");c.trigger(d,"fetch-error",b,1)})})}function ob(a,b,c){T(a.element,"viewer").whenFirstVisible().then(function(){return vb(a,b,c)}).then(function(c){return qb(a,c,b)})}
function qb(a,b,c){if(void 0===b||null===b)return Promise.resolve();var d=B(a.element.id,"<amp-state> must have an id.");return cb(a.element).then(function(a){var e=C();e[d]=b;a.setState(e,c,!c)})}l.S=function(){return"<amp-state> "+(this.element.getAttribute("id")||"<unknown id>")};var wb=/(\S+)(?:\s+(?:(-?\d+(?:\.\d+)?)([a-zA-Z]*)))?\s*(?:,|$)/g;function xb(a){for(var b=[],c;c=wb.exec(a);){var d=c[1],e=void 0,f=void 0;if(c[2]){var g=c[3].toLowerCase();if("w"==g)e=parseInt(c[2],10);else if("x"==g)f=parseFloat(c[2]);else continue}else f=1;b.push({url:d,width:e,dpr:f})}return new yb(b)}
function yb(a){B(0<a.length,"Srcset must have at least one source");this.N=a;for(var b=!1,c=!1,d=0;d<a.length;d++){var e=a[d];b=b||!!e.width;c=c||!!e.dpr}B(!!(b^c),"Srcset must have width or dpr sources, but not both");a.sort(b?zb:Ab);this.pa=b}
yb.prototype.select=function(a,b){if(this.pa){b*=a;a=this.N;for(var c=0,d=Infinity,e=Infinity,f=0;f<a.length;f++){var g=a[f].width,h=Math.abs(g-b);if(h<=1.1*d||1.2<b/e)c=f,d=h,e=g;else break}b=c}else{a=this.N;c=0;d=Infinity;for(e=0;e<a.length;e++)if(f=Math.abs(a[e].dpr-b),f<=d)c=e,d=f;else break;b=c}return this.N[b].url};yb.prototype.getUrls=function(){return this.N.map(function(a){return a.url})};
yb.prototype.stringify=function(a){for(var b=[],c=this.N,d=0;d<c.length;d++){var e=c[d],f=e.url;a&&(f=a(f));f=this.pa?f+(" "+e.width+"w"):f+(" "+e.dpr+"x");b.push(f)}return b.join(", ")};function zb(a,b){B(a.width!=b.width,"Duplicate width: %s",a.width);return a.width-b.width}function Ab(a,b){B(a.dpr!=b.dpr,"Duplicate dpr: %s",a.dpr);return a.dpr-b.dpr};var Bb={"class":{blacklistedValueRegex:"(^|\\W)i-amphtml-"},hidden:null,text:null},Cb={width:null,height:null},Db={"AMP-AUTOCOMPLETE":{src:{allowedProtocols:{https:!0}}},"AMP-BASE-CAROUSEL":{"advance-count":null,"auto-advance-count":null,"auto-advance-interval":null,"auto-advance-loops":null,"auto-advance":null,horizontal:null,"initial-index":null,loop:null,"mixed-length":null,"side-slide-count":null,slide:null,"snap-align":null,"snap-by":null,snap:null,"visible-count":null},"AMP-BRIGHTCOVE":{"data-account":null,
"data-embed":null,"data-player":null,"data-player-id":null,"data-playlist-id":null,"data-video-id":null},"AMP-CAROUSEL":{slide:null},"AMP-DATE-PICKER":{max:null,min:null,src:{allowedProtocols:{https:!0}}},"AMP-GOOGLE-DOCUMENT-EMBED":{src:null,title:null},"AMP-IFRAME":{src:null},"AMP-IMG":{alt:null,attribution:null,src:{allowedProtocols:{data:!0,http:!0,https:!0}},srcset:{alternativeName:"src"}},"AMP-LIGHTBOX":{open:null},"AMP-LIST":{src:{allowedProtocols:{https:!0}},state:null,"is-layout-container":null},
"AMP-SELECTOR":{disabled:null,selected:null},"AMP-STATE":{src:{allowedProtocols:{https:!0}}},"AMP-TIMEAGO":{datetime:null,title:null},"AMP-VIDEO":{alt:null,attribution:null,controls:null,loop:null,poster:null,preload:null,src:{allowedProtocols:{https:!0}}},"AMP-YOUTUBE":{"data-videoid":null},A:{href:{allowedProtocols:{ftp:!0,http:!0,https:!0,mailto:!0,"fb-messenger":!0,intent:!0,skype:!0,sms:!0,snapchat:!0,tel:!0,tg:!0,threema:!0,twitter:!0,viber:!0,whatsapp:!0}}},BUTTON:{disabled:null,type:null,
value:null},DETAILS:{open:null},FIELDSET:{disabled:null},IMAGE:{"xlink:href":{allowedProtocols:{http:!0,https:!0}}},INPUT:{accept:null,accesskey:null,autocomplete:null,checked:null,disabled:null,height:null,inputmode:null,max:null,maxlength:null,min:null,minlength:null,multiple:null,pattern:null,placeholder:null,readonly:null,required:null,selectiondirection:null,size:null,spellcheck:null,step:null,type:{blacklistedValueRegex:"(^|\\s)(button|image|)(\\s|$)"},value:null,width:null},OPTION:{disabled:null,
label:null,selected:null,value:null},OPTGROUP:{disabled:null,label:null},SECTION:{"data-expand":null},SELECT:{autofocus:null,disabled:null,multiple:null,required:null,size:null},SOURCE:{src:{allowedProtocols:{https:!0}},type:null},TRACK:{label:null,src:{allowedProtocols:{https:!0}},srclang:null},TEXTAREA:{autocomplete:null,autofocus:null,cols:null,disabled:null,maxlength:null,minlength:null,pattern:null,placeholder:null,readonly:null,required:null,rows:null,selectiondirection:null,selectionend:null,
selectionstart:null,spellcheck:null,wrap:null,defaulttext:null}},Eb={src:!0,srcset:!0,href:!0,"xlink:href":!0};function Fb(a){this.ra=a}Fb.prototype.canBind=function(a,b){return void 0!==Gb(this,a,b)};
Fb.prototype.isResultValid=function(a,b,c){var d=Gb(this,a,b);d&&d.alternativeName&&(d=Gb(this,a,d.alternativeName));if(void 0===d)return!1;if(null===d)return!0;if(c&&E(Eb,b)){if("srcset"===b){try{var e=xb(c)}catch(k){return y().error("amp-bind","Failed to parse srcset: ",k),!1}var f=e.getUrls()}else f=[c];for(a=0;a<f.length;a++){a:{var g=f[a];b=d;if(g){if(/__amp_source_origin/.test(g)){b=!1;break a}if(b=b.allowedProtocols)if(g=/^([^:\/?#.]+):[\s\S]*$/.exec(g),null!==g&&(g=g[1].toLowerCase().trim(),
!pa.call(b,g))){b=!1;break a}}b=!0}if(!b)return!1}}var h=d.blacklistedValueRegex;if(c&&h){var n=new RegExp(h,"i");if(n.test(c))return!1}return!0};function Gb(a,b,c){if(F(c,"aria-"))return null;if(!E(Eb,c)||a.ra){var d=E(Bb,c);if(void 0!==d)return d;var e=E(Cb,c);if(F(b,"AMP-")&&void 0!==e)return e;var f=E(Db,b);if(f)return f[c]}};var Hb=!1;function Ib(a){if(!Hb){Hb=!0;a=a.body;var b={opacity:1,visibility:"visible",animation:"none"},c;for(c in b){var d=a,e=b[c];var f=d.style;var g=c;if(F(g,"--"))f=g;else{G||(G=C());var h=G[g];if(!h){h=g;if(void 0===f[g]){var n=g;n=n.charAt(0).toUpperCase()+n.slice(1);b:{for(var k=0;k<ra.length;k++){var z=ra[k]+n;if(void 0!==f[z]){n=z;break b}}n=""}void 0!==f[n]&&(h=n)}G[g]=h}f=h}f&&(d.style[f]=e)}}};function U(){this.o=[]}U.prototype.peek=function(){var a=this.o.length;return a?this.o[a-1].item:null};U.prototype.enqueue=function(a,b){if(isNaN(b))throw Error("Priority must not be NaN.");for(var c=b,d=-1,e=0,f=this.o.length;e<=f;){d=Math.floor((e+f)/2);if(d===this.o.length)break;if(this.o[d].priority<c)e=d+1;else if(0<d&&this.o[d-1].priority>=c)f=d-1;else break}this.o.splice(d,0,{item:a,priority:b})};U.prototype.forEach=function(a){for(var b=this.o.length;b--;)a(this.o[b].item)};
U.prototype.dequeue=function(){return this.o.length?this.o.pop().item:null};ia.Object.defineProperties(U.prototype,{length:{configurable:!0,enumerable:!0,get:function(){return this.o.length}}});var Jb=/nochunking=1/.test(self.location.hash),Kb=Promise.resolve();function Lb(a,b){if(Jb)Kb.then(b);else{var c=Mb,d=P(a),e=Q(d);Na(e,d,"chunk",c);T(a,"chunk").run(b,10)}}function V(a){this.state="not_run";this.$=a}function Nb(a,b){if("run"!=a.state){a.state="run";try{a.$(b)}catch(c){throw a.ja(),c;}}}V.prototype.S=function(){return this.$.displayName||this.$.name};V.prototype.ja=function(){};V.prototype.ia=function(){return!1};V.prototype.na=function(){return!0};
function W(a,b,c){V.call(this,a);this.h=b;this.Z=c}ha(W,V);W.prototype.ja=function(){Ib(self.document)};W.prototype.ia=function(){return this.Z.viewer?this.Z.viewer.isVisible():this.h.document.hidden?!1:!/visibilityState=(hidden|prerender)/.test(this.h.location.hash)};W.prototype.na=function(){return!!this.Z.viewer};
function Mb(a){var b=this;this.h=a.win;this.K=new U;this.fa=this.ga.bind(this);this.L=0;this.Aa=Ga(this.h,"macro-after-long-task");this.V=!1;this.sa=this.h.document.documentElement.hasAttribute("i-amphtml-no-boilerplate");this.h.addEventListener("message",function(a){"amp-macro-task"==a.data&&b.ga(null)});this.Ea=Ra(Q(a),"viewer");this.viewer=null;this.Ea.then(function(a){b.viewer=a;a.onVisibilityChanged(function(){a.isVisible()&&Ob(b)})})}
Mb.prototype.run=function(a,b){var c=new V(a);this.K.enqueue(c,b);Ob(this)};Mb.prototype.runForStartup=function(a){a=new W(a,this.h,this);this.K.enqueue(a,Number.POSITIVE_INFINITY);Ob(this)};function Pb(a,b){for(var c=a.K.peek();c&&"not_run"!==c.state;)a.K.dequeue(),c=a.K.peek();c&&b&&a.K.dequeue();return c}
Mb.prototype.ga=function(a){var b=this,c=Pb(this,!0);if(!c)return this.V=!1,this.L=0,!1;try{var d=Date.now();Nb(c,a)}finally{Kb.then().then().then().then().then().then().then().then().then(function(){b.V=!1;b.L+=Date.now()-d;Ob(b)})}return!0};function Qb(a){a.Aa&&a.sa&&5<a.L?(a.L=0,Rb(a)):Kb.then(function(){a.fa(null)})}function Ob(a){if(!a.V){var b=Pb(a);b&&(b.ia()?(a.V=!0,Qb(a)):b.na()&&a.h.requestIdleCallback?Sb(a.h,a.fa):Rb(a))}}function Rb(a){a.h.postMessage("amp-macro-task","*")}
function Sb(a,b){function c(f){if(f.timeRemaining()<d){var g=2E3-(Date.now()-e);0>=g||f.didTimeout?b(f):a.requestIdleCallback(c,{timeout:g})}else b(f)}var d=15,e=Date.now();a.requestIdleCallback(c,{timeout:2E3})};function Tb(){this.F=C();this.j=null}l=Tb.prototype;l.get=function(a){a=this.F[a];return null==a?null:a};l.whenSignal=function(a){var b=this.j&&this.j[a];if(!b){var c=this.F[a];null!=c?b={promise:"number"==typeof c?Promise.resolve(c):Promise.reject(c)}:(c=new J,b={promise:c.promise,resolve:c.resolve,reject:c.reject});this.j||(this.j=C());this.j[a]=b}return b.promise};
l.signal=function(a,b){if(null==this.F[a]){var c=b||Date.now();this.F[a]=c;(a=this.j&&this.j[a])&&a.resolve&&(a.resolve(c),a.resolve=void 0,a.reject=void 0)}};l.rejectSignal=function(a,b){null==this.F[a]&&(this.F[a]=b,(a=this.j&&this.j[a])&&a.reject&&(a.reject(b),a.resolve=void 0,a.reject=void 0))};l.reset=function(a){this.F[a]&&delete this.F[a];var b=this.j&&this.j[a];b&&!b.resolve&&delete this.j[a]};function Ub(a,b,c){function d(){e=0;var h=c-(a.Date.now()-f);if(0<h)e=a.setTimeout(d,h);else{var n=g;g=null;b.apply(null,n)}}var e=0,f=0,g=null;return function(b){for(var h=[],k=0;k<arguments.length;++k)h[k-0]=arguments[k];f=a.Date.now();g=h;e||(e=a.setTimeout(d,c))}};function Vb(a,b,c){var d="ww";b?(b=a.protocol+"//"+a.host,"about:"==a.protocol&&(b=""),a=b+"/dist"):a=w.cdn;return c?(b=t().singlePassType?t().singlePassType+"/":"",a+"/rtv/"+t().rtvVersion+"/"+b+d+".js"):a+"/"+d+".js"};function Wb(a){var b=this;this.h=a;this.Fa=R(a,"xhr");var c=a.location,d=!1,e=!d,f=Vb(c,d,e);this.da=null;this.ha=this.Fa.fetchText(f,{ampCors:!1,bypassInterceptorForDev:!1}).then(function(a){return a.text()}).then(function(c){c=new a.Blob([c+"\n//# sourceurl="+f],{type:"text/javascript"});var d=a.URL.createObjectURL(c);b.da=new a.Worker(d);b.da.onmessage=b.Ca.bind(b)});this.U={};this.ua=0;this.qa=[a]}
function Xb(a,b,c,d){return a.ha.then(function(){return new Promise(function(e,f){var g=a.ua++;a.U[g]={method:b,resolve:e,reject:f};e=d||a.h;f=a.qa.indexOf(e);var h=0<=f?f:a.qa.push(e)-1;a.da.postMessage({method:b,args:c,scope:h,id:g})})})}Wb.prototype.Ca=function(a){var b=a.data;a=b.method;var c=b.returnValue;b=b.id;var d=this.U[b];d?(d.resolve(c),delete this.U[b]):A().error("web-worker","Received unexpected message ("+a+", "+b+") from worker.")};
Wb.prototype.hasPendingMessages=function(){return 0<Object.keys(this.U).length};Wb.prototype.Ga=function(){return this.ha};function Yb(a){var b=["\u26a14email","amp4email"],c=a.documentElement,d=b.some(function(a){return c.hasAttribute(a)});return d};function Zb(){var a=1.5,b=$b(a);return function(a){return setTimeout(a,b())}}function $b(a){var b=a||2,c=0;return function(){var a=Math.pow(b,c++);var e=a*(e||.3)*Math.random();.5<Math.random()&&(e*=-1);a+=e;return 1E3*a}};var X=self.AMPErrors||[];self.AMPErrors=X;function ac(a){ac=Zb();return ac(a)}function bc(a){try{return JSON.stringify(a)}catch(b){return String(a)}}var cc;
function Y(a,b){try{if(a)if(void 0!==a.message)a=oa(a);else{var c=a;a=Error(bc(c));a.origError=c}else a=Error("Unknown error");if(!a.reported){a.reported=!0;var d=b||a.associatedElement;d&&d.classList&&(d.classList.add("i-amphtml-error"),t().development&&(d.classList.add("i-amphtml-element-error"),d.setAttribute("error-message",a.message)));if(self.console){var e=console.error||console.log;a.messageArray?e.apply(console,a.messageArray):d?e.call(console,a.message,d):e.call(console,a.message)}d&&d.ya&&
d.ya("amp:error",a.message);dc.call(void 0,void 0,void 0,void 0,void 0,a)}}catch(f){setTimeout(function(){throw f;})}}function dc(a,b,c,d,e){var f=this;this&&this.document&&Ib(this.document);if(!t().development){var g=!1;try{g=ec()}catch(n){}if(!(g&&.01<Math.random())){var h=fc(a,b,c,d,e,g);h&&ac(function(){try{return gc(f,h).catch(function(){})}catch(n){}})}}}
function gc(a,b){return hc(a,b).then(function(a){if(!a){var c=new XMLHttpRequest;c.open("POST",w.errorReporting,!0);c.send(JSON.stringify(b))}})}
function hc(a,b){var c=R(a,"ampdoc");if(!c.isSingleDoc())return Promise.resolve(!1);a=c.getSingleDoc();if(!a.getRootNode().documentElement.hasAttribute("report-errors-to-viewer"))return Promise.resolve(!1);var d=T(a,"viewer");return d.hasCapability("errorReporter")?d.isTrustedViewer().then(function(a){if(!a)return!1;d.sendMessage("error",D({m:b.m,a:b.a,s:b.s,el:b.el,ex:b.ex,v:b.v,jse:b.jse}));return!0}):Promise.resolve(!1)}
function fc(a,b,c,d,e,f){var g=a;e&&(g=e.message?e.message:String(e));g||(g="Unknown error");a=g;var h=!(!e||!e.expected);if(!/_reported_/.test(a)&&"CANCELLED"!=a){var n=!(self&&self.window),k=Math.random();if(-1!=a.indexOf("Failed to load:")||"Script error."==a||n)if(h=!0,.001<k)return;var z=0<=a.indexOf("\u200b\u200b\u200b");if(!(z&&.1<k)){g=Object.create(null);g.v=t().rtvVersion;g.noAmp=f?"1":"0";g.m=a.replace("\u200b\u200b\u200b","");g.a=z?"1":"0";g.ex=h?"1":"0";g.dw=n?"1":"0";var p="1p";self.context&&
self.context.location?(g["3p"]="1",p="3p"):t().runtime&&(p=t().runtime);t().singlePassType&&(g.spt=t().singlePassType);g.rt=p;"inabox"===p&&(g.adid=t().a4aId);f=self;g.ca=f.AMP_CONFIG&&f.AMP_CONFIG.canary?"1":"0";f=self;g.bt=f.AMP_CONFIG&&f.AMP_CONFIG.type?f.AMP_CONFIG.type:"unknown";self.location.ancestorOrigins&&self.location.ancestorOrigins[0]&&(g.or=self.location.ancestorOrigins[0]);self.viewerState&&(g.vs=self.viewerState);self.parent&&self.parent!=self&&(g.iem="1");if(self.AMP&&self.AMP.viewer){var m=
self.AMP.viewer.getResolvedViewerUrl(),H=self.AMP.viewer.maybeGetMessagingOrigin();m&&(g.rvu=m);H&&(g.mso=H)}cc||(cc=ic());g.jse=cc;var S=[];f=self.__AMP__EXPERIMENT_TOGGLES||null;for(var r in f)S.push(r+"="+(f[r]?"1":"0"));g.exps=S.join(",");e?(g.el=e.associatedElement?e.associatedElement.tagName:"u",e.args&&(g.args=JSON.stringify(e.args)),z||e.ignoreStack||!e.stack||(g.s=e.stack),e.message&&(e.message+=" _reported_")):(g.f=b||"",g.l=c||"",g.c=d||"");g.r=self.document?self.document.referrer:"";g.ae=
X.join(",");g.fr=self.location.originalHash||self.location.hash;b=a;25<=X.length&&X.splice(0,X.length-25+1);X.push(b);return g}}}function ec(){var a=self;if(!a.document)return!1;a=a.document.querySelectorAll("script[src]");for(var b=0;b<a.length;b++)if(!M(a[b].src.toLowerCase()))return!0;return!1}
function ic(){function a(){}a.prototype.t=function(){throw Error("message");};var b=new a;try{b.t()}catch(d){b=d.stack;if(F(b,"t@"))return"Safari";if(-1<b.indexOf(".prototype.t@"))return"Firefox";var c=b.split("\n").pop();if(/\bat .* \(/i.test(c))return"IE";if(F(b,"Error: message"))return"Chrome"}return"unknown"};function jc(a,b,c){var d=self.location;Fa(c);var e=M(d),f=L(Da(d));if("href"==b&&!F(c,"#"))return Ea(c,f);if("src"==b)return"amp-img"==a?kc(c,f,e):Ea(c,f);if("srcset"==b){try{var g=xb(c)}catch(h){return y().error("URL-REWRITE","Failed to parse srcset: ",h),c}return g.stringify(function(a){return kc(a,f,e)})}return c}
function kc(a,b,c){a=L(Ea(a,b));return"data:"==a.protocol||M(a)||!c?a.href:w.cdn+"/i/"+("https:"==a.protocol?"s/":"")+encodeURIComponent(a.host)+a.pathname+(a.search||"")+(a.hash||"")};function lc(a){return"loading"!=a.readyState&&"uninitialized"!=a.readyState}function mc(a,b){var c=lc,d=c(a);if(d)b(a);else{var e=function(){c(a)&&(d||(d=!0,b(a)),a.removeEventListener("readystatechange",e))};a.addEventListener("readystatechange",e)}}function nc(a){return new Promise(function(b){mc(a,b)})};var oc=/^(i?-)?amp(html)?-/,pc={INPUT:{checked:!0,value:!0},OPTION:{selected:!0},TEXTAREA:{text:!0}},qc=C({"AMP-CAROUSEL":["slide"],"AMP-LIST":["state","is-layout-container"],"AMP-SELECTOR":["selected"]}),rc=["AMP-LIST"];
function sc(a,b){var c=this;this.ampdoc=a;this.h=a.win;this.I=b||a.win;this.Y=[];this.za=Ub(this.h,function(){c.Y.length=0},5E3);this.C=[];this.D=C();this.aa=T(a,"history");this.ka=[];this.J=1E3;this.la=T(a,"resources");this.w=C();this.Da=R(this.h,"timer");this.oa=null;this.O=T(this.ampdoc,"viewer");this.O.onMessageRespond("premutate",this.Ba.bind(this));this.M=this.O.whenFirstVisible().then(function(){if(b){var c=b.document;return nc(c).then(function(){return c})}return a.whenReady().then(function(){return a.getRootNode()})}).then(function(a){return tc(c,
a)});this.ea=new J;this.W=null;this.ma=new Tb;this.H=[];this.va=Ub(this.h,function(){return uc(c)},1E3);var d=self.AMP;d.printState=d.printState||this.xa.bind(this);d.setState=d.setState||function(a){return c.setState(a)};d.eval=d.eval||this.wa.bind(this)}sc.installInEmbedWindow=function(a,b){Ma(a,new sc(b,a))};l=sc.prototype;l.signals=function(){return this.ma};
l.setState=function(a,b,c){var d=this;A().info("amp-bind","setState (init=%s):",b,a);try{qa(this.w,a)}catch(e){y().error("amp-bind","Failed to merge result from AMP.setState().",e)}return b?Promise.resolve():this.W=this.M.then(function(){return vc(d)}).then(function(a){return wc(d,a,c)})};
l.invoke=function(a){var b=a,c=b.args,d=b.event,e=b.method,f=b.sequenceId,g=b.tagOrTarget;if(this.Y.includes(f))return y().error("amp-bind","One state action allowed per event."),Promise.resolve();this.Y.push(f);this.za();if(b=c.__AMP_OBJECT_STRING__)switch(this.J=Math.min(2E3,Math.max(1E3,this.J+500)),this.ma.signal("FIRST_MUTATE"),c={},d&&d.detail&&(c.event=d.detail),e){case "setState":return this.setStateWithExpression(b,c);case "pushState":return this.pushStateWithExpression(b,c);default:return Promise.reject(A().createError("Unrecognized method: %s.%s",
g,e))}else y().error("AMP-BIND","Please use the object-literal syntax, e.g. \"AMP.setState({foo: 'bar'})\" instead of \"AMP.setState(foo='bar')\".");return Promise.resolve()};l.setStateWithExpression=function(a,b){var c=this;A().info("amp-bind","setState:",a);return this.W=xc(this,a,b).then(function(a){return c.setState(a)}).then(function(){return yc(c).then(function(a){a&&zc(c,{op:0,data:a})})})};
l.pushStateWithExpression=function(a,b){var c=this;A().info("amp-bind","pushState:",a);return xc(this,a,b).then(function(a){function b(){return c.setState(d)}var d=C();Object.keys(a).forEach(function(a){d[a]=Ac(c.w[a])});return c.setState(a).then(function(){return yc(c).then(function(a){zc(c,{op:1,data:a,onPop:b})})})})};function zc(a,b){var c=!0;if(0===b.op&&0<a.H.length){var d=a.H[a.H.length-1];0===d.op&&(d.data=b.data,c=!1)}c&&a.H.push(b);1===b.op?uc(a):a.va()}
function uc(a){a.H.forEach(function(b){var c=b.op,d=b.data;b=b.onPop;0===c?a.aa.replace(d):1===c&&a.aa.push(b,d)});a.H.length=0}function yc(a){var b=D({data:D({"amp-bind":Ac(a.w)}),title:a.I.document.title});return a.O.isEmbedded()?a.O.isTrustedViewer().then(function(a){return a?b:void 0}):Promise.resolve(b)}l.rescan=function(a,b,c){var d=this;c=void 0===c?{}:c;var e=c.fast?this.ea.promise:this.M;return e.then(function(){return d.Da.timeoutPromise(c.timeout||2E3,Bc(d,a,b,c),"Timed out waiting for amp-bind to rescan.")})};
function Bc(a,b,c,d){A().info("amp-bind","rescan: ",b,c,d);var e=d.fast?Cc(a,b,c):Dc(a,b,c);return e.then(function(){if(d.update)return vc(a).then(function(c){return Ec(a,c,b)})})}
function Cc(a,b,c){var d=Fc(a,c),e=[],f=b.filter(function(a){return a.hasAttribute("i-amphtml-binding")});b.forEach(function(a){a=a.querySelectorAll("[i-amphtml-binding]");Array.prototype.push.apply(f,a)});var g=a.J-a.numberOfBindings();for(b=0;b<f.length&&!Gc(a,f[b],g-e.length,e);b++);d.then(function(b){A().info("amp-bind","rescan.fast: delta=%s, total=%s",e.length-b,a.numberOfBindings())});return 0<e.length?Hc(a,e):Promise.resolve()}
l.getStateValue=function(a){a=eb(this.w,a);return na(a)||Array.isArray(a)?JSON.stringify(a):String(a)};
function tc(a,b){var c=!Yb(a.I.document);a.oa=new Fb(c);return Z(a,"bind.init",[c]).then(function(){return Promise.all([Ic(a).then(function(){return a.ea.resolve()}),Jc(a,[b])])}).then(function(){b.addEventListener("amp:dom-update",function(b){return Kc(a,b)})}).then(function(){var a=b.querySelectorAll("AMP-STATE"),c=!1,f=u(a).map(function(a){return $a(a).then(function(){return a.getImpl(c)}).then(function(a){return a.parseAndUpdate()})});return Promise.all(f)}).then(function(){if(t().development)return vc(a).then(function(b){return Lc(a,
b)});a.O.sendMessage("bindReady",void 0)})}l.numberOfBindings=function(){return this.C.reduce(function(a,b){return a+b.boundProperties.length},0)};l.Ja=function(a){this.J=a};l.Ha=function(){return this.aa};
l.Ba=function(a){var b=this,c=[];return this.M.then(function(){Object.keys(a.state).forEach(function(d){b.ka.includes(d)||(delete a.state[d],c.push(d))});0<c.length&&y().warn("amp-bind","Some state keys could not be premutated because they are missing the overridable attribute: "+c.join(", "));return b.setState(a.state)})};l.addOverridableKey=function(a){this.ka.push(a)};
function Ic(a){var b=a.ampdoc.getBody().querySelectorAll("AMP-BIND-MACRO"),c=[];Ya(b,function(a){var b=(a.getAttribute("arguments")||"").split(",").map(function(a){return a.trim()});c.push({id:a.getAttribute("id"),argumentNames:b,expressionString:a.getAttribute("expression")})});return 0==c.length?Promise.resolve(0):Z(a,"bind.addMacros",[c]).then(function(a){a.forEach(function(a,c){Mc(a,"amp-bind: Parsing amp-bind-macro failed.",b[c])});return c.length})}
function Jc(a,b){if(!b.length)return Promise.resolve(0);var c=b.map(function(b){var c=a.J-a.numberOfBindings();return Nc(a,b,c).then(function(b){var c=b.bindings,d=b.limitExceeded;d&&A().expectedError("amp-bind","Maximum number of bindings reached (%s). Additional elements with bindings will be ignored.",a.J);return c})});return Promise.all(c).then(function(b){b=Array.prototype.concat.apply([],b);return 0<b.length?Hc(a,b):0})}
function Hc(a,b){return Z(a,"bind.addBindings",[b]).then(function(c){Object.keys(c).forEach(function(b){var d=a.D[b];0<d.length&&Mc(c[b],'amp-bind: Expression compile error in "'+b+'".',d[0])});return b.length})}
function Fc(a,b){if(!b.length)return Promise.resolve(0);kb(a.C,function(a){for(var c=0;c<b.length;c++)if(b[c].contains(a.element))return!0;return!1});var c=[],d;for(d in a.D){var e=a.D[d];kb(e,function(a){for(var c=0;c<b.length;c++)if(b[c].contains(a))return!0;return!1});0==e.length&&(c.push(d),delete a.D[d])}var f=c.length;return 0<f?Z(a,"bind.removeBindingsWithExpressionStrings",[c]).then(function(){return f}):Promise.resolve(0)}
function Nc(a,b,c){function d(){var b=f.currentNode;if(!b)return!0;if(b.nodeType!==Node.ELEMENT_NODE)return!f.nextNode();var d=c-e.length;Gc(a,b,d,e)&&(g=!0);if(rc.includes(b.nodeName))a:{b=f;for(var k=b.currentNode;k;k=b.parentNode())if(k=b.nextSibling()){b=k;break a}b=null}else b=f.nextNode();var z=b;return!z||g}var e=[],f=(b.nodeType==Node.DOCUMENT_NODE?b:b.ownerDocument).createTreeWalker(b,NodeFilter.SHOW_ELEMENT,null,!1),g=!1;return new Promise(function(b){function c(f){var h=!1;if(f&&!f.didTimeout)for(;1<
f.timeRemaining()&&!h;)h=d();else{var p=250;for(f=0;f<p&&!h;f++)h=d()}h?b({bindings:e,limitExceeded:g}):Lb(a.ampdoc,c)}Lb(a.ampdoc,c)})}function Gc(a,b,c,d){var e=!1,f=Oc(a,b);f.length>c&&(f.length=c,e=!0);0<f.length&&a.C.push({element:b,boundProperties:f});var g=b.tagName;f.forEach(function(c){var e=c,f=e.expressionString;d.push({tagName:g,property:e.property,expressionString:f});a.D[f]||(a.D[f]=[]);a.D[f].push(b)});return e}
function Oc(a,b){for(var c=[],d=b.attributes,e=0,f=d.length;e<f;e++){a:{var g=void 0,h=a,n=d[e];var k=b;var z=k.tagName,p=n.name;if(2<p.length&&"["===p[0]&&"]"===p[p.length-1])g=p.substr(1,p.length-2);else if(F(p,"data-amp-bind-")&&(g=p.substr(14),k.hasAttribute("["+g+"]"))){k=null;break a}if(g){if(h.oa.canBind(z,g)){k={property:g,expressionString:n.value};break a}g=y().createError("%s: Binding to [%s] on <%s> is not allowed.","amp-bind",g,z);Y(g,k)}k=null}k&&c.push(k)}return c}
function xc(a,b,c){return a.M.then(function(){Object.assign(c,a.w);return Z(a,"bind.evaluateExpression",[b,c])}).then(function(a){var b=a.result;if(a=a.error)throw Mc(a,"amp-bind: Expression eval failed.");return b})}
function vc(a){var b=Z(a,"bind.evaluateBindings",[a.w]);return b.then(function(b){var c=b.results,e=b.errors;Object.keys(e).forEach(function(b){var c=a.D[b];if(0<c.length){var d=e[b],f=y().createError('%s: Expression evaluation error in "%s". %s',"amp-bind",b,d.message);f.stack=d.stack;Y(f,c[0])}});A().info("amp-bind","evaluation:",c);return c})}
function Lc(a,b){var c=void 0===c?null:c;var d=void 0===d?!0:d;var e={};a.C.forEach(function(a){var f=a.element;a=a.boundProperties;c&&!Pc(c,f)||a.forEach(function(a){var c=b[a.expressionString];if(void 0!==c){var g=a.property,h=qc[f.tagName];if(h&&h.includes(g))c=null;else{switch(g){case "text":g=f.textContent;c=String(c);h=g.trim()===c.trim();break;case "class":g=[];for(h=0;h<f.classList.length;h++){var p=f.classList[h];oc.test(p)||g.push(p)}p=[];Array.isArray(c)?p=c:"string"===typeof c?(h=c.trim(),
0<h.length&&(p=h.split(" "))):(h=y().createError('%s: "%s" is not a valid result for [class].',"amp-bind",c),Y(h,f));b:{h=g;var m=p;if(h.length!==m.length)h=!1;else{p=(Array.isArray(h)?h:u(h)).sort();m=(Array.isArray(m)?m:u(m)).sort();for(var H=0;H<h.length;H++)if(p[H]!==m[H]){h=!1;break b}h=!0}}break;default:g=f.getAttribute(g),h=!0===c?""===g:!1===c?null===g:"number"===typeof c?Number(g)===c:g===c}c=h?null:{expected:c,actual:g}}var S=c;if(S){c=f.tagName;g=a.property;a=a.expressionString;h=S;p=h.expected;
var r=h.actual;e[c+"["+g+"]"+p+":"+r]=!0;d&&y().warn("amp-bind","Default value ("+r+") does not match first result ("+(p+") for <"+c+" ["+g+']="')+(a+'">. We recommend writing expressions with matching default values, but this can be safely ignored if intentional.'))}}})});return Object.keys(e)}function Pc(a,b){for(var c=0;c<a.length;c++)if(a[c].contains(b))return!0;return!1}
function Qc(a,b){var c=[];a.forEach(function(a){var d=a.previousResult,f=b[a.expressionString];void 0===f||gb(f,d)||(a.previousResult=f,c.push({boundProperty:a,newValue:f}))});return c}function wc(a,b,c){var d=a.C.map(function(d){return c&&"AMP-STATE"===d.element.tagName?Promise.resolve():Rc(a,b,d)});return Promise.all(d)}function Ec(a,b,c){var d=[];a.C.forEach(function(e){c.forEach(function(c){c.contains(e.element)&&d.push(Rc(a,b,e))})});return Promise.all(d)}
function Rc(a,b,c){var d=c.element,e=Qc(c.boundProperties,b);return 0===e.length?Promise.resolve():a.la.mutateElement(d,function(){var b=C(),c,h;e.forEach(function(e){var f=e,g=f.boundProperty,m=f.newValue;f=g.property;a:{g=g.property;var k=d.tagName;switch(g){case "defaulttext":d.textContent=String(m);break;case "text":g=String(m);"TITLE"===k&&d.parentNode===a.I.document.head&&(a.I.document.title=g);"TEXTAREA"===k?d.value=g:d.textContent=g;break;case "class":g=[];for(var n=0;n<d.classList.length;n++){var r=
d.classList[n];oc.test(r)&&g.push(r)}Array.isArray(m)||"string"===typeof m?d.setAttribute("class",g.concat(m).join(" ")):null===m?d.setAttribute("class",g.join(" ")):(g=y().createError('%s: "%s" is not a valid result for [class].',"amp-bind",m),Y(g,d));break;default:var rb="INPUT"===k&&g in d,I=d.getAttribute(g);k=!1;if("boolean"===typeof m){if(rb&&d[g]!==m&&(d[g]=m,k=!0),m&&""!==I?(d.setAttribute(g,""),k=!0):m||null===I||(d.removeAttribute(g),k=!0),k&&"OPTION"===d.tagName&&"selected"===g&&m&&R(a.h,
"platform").isSafari()&&(n=Xa(d,"select")))r=u(n.options).indexOf(d),0<=r&&(n.selectedIndex=r)}else if("object"===typeof m&&null!==m)k=!0;else if(m!==I)b:{I=String(m);try{n=d.tagName.toLowerCase();r=g.toLowerCase();var Ha="src"==r||"href"==r||"srcset"==r?jc(n,r,I):I;if(M(self.location)&&"a"===n&&"href"===r){var sb=d.getAttribute(r),tb="#"===Ha[0],ub=sb&&"#"===sb[0];tb&&!ub?(d.__AMP_ORIGINAL_TARGET_VALUE_||(d.__AMP_ORIGINAL_TARGET_VALUE_=d.getAttribute("target")),d.removeAttribute("target")):ub&&!tb&&
d.setAttribute("target",d.__AMP_ORIGINAL_TARGET_VALUE_||"_top")}rb&&(d[r]=Ha);d.setAttribute(r,Ha);k=!0;break b}catch(Sc){n=y().createError('%s: "%s" is not a valid result for [%]',"amp-bind",I,g,Sc),Y(n,d)}k=!1}if(k){g={name:g,value:m};break a}}g=null}var Ia=g;Ia&&(b[Ia.name]=Ia.value,"width"==f?c="number"===typeof m&&isFinite(m)?Number(m):c:"height"==f&&(h="number"===typeof m&&isFinite(m)?Number(m):h));(m=pc[d.tagName])&&m[f]&&(f="OPTION"===d.tagName?Xa(d,"SELECT"):d)&&(m=jb(a.I,"amp:form-value-change",
null,{bubbles:!0}),f.dispatchEvent(m))});void 0===c&&void 0===h||a.la.changeSize(d,h,c);if("function"===typeof d.mutatedAttributesCallback)try{d.mutatedAttributesCallback(b)}catch(k){var n=y().createError("%s: Applying expression results (%s) failed with error,","amp-bind",JSON.stringify(b),k);Y(n,d)}})}function Kc(a,b){b=b.target;var c=b.parentNode;c&&rc.includes(c.nodeName)||(A().info("amp-bind","dom_update:",b),Dc(a,[b],[b],"dom_update.end").then(function(){}))}
function Dc(a,b,c,d){d=void 0===d?"rescan.slow":d;var e=0;return Fc(a,c).then(function(c){e=c;return Jc(a,b)}).then(function(b){A().info("amp-bind","%s: delta=%s, total=%s",d,b-e,a.numberOfBindings())})}function Z(a,b,c){var d=a.h;a=a.I;if(d.Worker){var e=N(d);Na(e,e,"amp-worker",Wb);d=R(d,"amp-worker");b=Xb(d,b,c||[],a)}else b=Promise.reject("Worker not supported in window.");return b}function Mc(a,b,c){b=y().createError("%s %s",b,a.message);b.stack=a.stack;Y(b,c);return b}
function Ac(a){if(void 0===a)return null;try{return JSON.parse(JSON.stringify(a))}catch(b){A().error("amp-bind","Failed to copy JSON ("+a+") with error: "+b)}return null}
l.xa=function(a){if(a)if("string"==typeof a){var b=eb(this.w,a);y().info("amp-bind",b)}else a.nodeType==Node.ELEMENT_NODE?(b=y().assertElement(a),Tc(this,b)):y().info("amp-bind",'Invalid argument. Pass a JSON expression or an element instead e.g. AMP.printState("foo.bar") or AMP.printState($0) after selecting an element.');else y().info("amp-bind",this.w)};
function Tc(a,b){var c=lb(a.C,function(a){return a.element==b});if(0>c)y().info("amp-bind","Element has no bindings:",b);else{var d=[],e=a.C[c].boundProperties;e.forEach(function(b){d.push(xc(a,b.expressionString,a.w))});Promise.all(d).then(function(a){var b=C();e.forEach(function(c,d){b[c.property]=a[d]});y().info("amp-bind",b)})}}l.wa=function(a){xc(this,a,this.w).then(function(a){y().info("amp-bind",a)})};l.Ia=function(){return this.M};l.Ka=function(){return this.W};(function(a){a.registerServiceForDoc("bind",sc);a.registerElement("amp-state",nb);a.registerElement("amp-bind-macro",ta)})(self.AMP);
})});

//# sourceMappingURL=amp-bind-0.1.js.map
