(self.AMP=self.AMP||[]).push({n:"amp-access",v:"1908231648370",f:(function(AMP,_){
var h;function m(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};function aa(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var ba=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function q(a){var b=Object.create(null);if(!a)return b;for(var c;c=ba.exec(a);){var d=aa(c[1],c[1]),e=c[2]?aa(c[2],c[2]):"";b[d]=e}return b};var ca="";
function da(){var a,b=a||self;if(b.__AMP_MODE)var c=b.__AMP_MODE;else{c=b;var d=self.AMP_CONFIG||{},e=!!d.test||!1,f=c.__karma__&&c.__karma__.config.amp.testOnIe,g=q(c.location.originalHash||c.location.hash);d=d.spt;var k=q(c.location.search);ca||(ca=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"011908231648370");c={localDev:!1,development:!(!["1","actions","amp","amp4ads","amp4email"].includes(g.development)&&!c.AMP_DEV_MODE),examiner:"2"==g.development,filter:g.filter,geoOverride:g["amp-geo"],userLocationOverride:g["amp-user-location"],
minified:!0,lite:void 0!=k.amp_lite,test:e,testIe:f,log:g.log,version:"1908231648370",rtvVersion:ca,singlePassType:d};c=b.__AMP_MODE=c}return c};var ea=Object.prototype.toString;var u=self.AMP_CONFIG||{},ha={thirdParty:u.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:u.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof u.thirdPartyFrameRegex?new RegExp(u.thirdPartyFrameRegex):u.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:u.cdnUrl||"https://cdn.ampproject.org",cdnProxyRegex:("string"==typeof u.cdnProxyRegex?new RegExp(u.cdnProxyRegex):u.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,
errorReporting:u.errorReportingUrl||"https://amp-error-reporting.appspot.com/r",localDev:u.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.dev$/]};self.log=self.log||{user:null,dev:null,userForEmbed:null};var w=self.log;function x(){if(!w.user)throw Error("failed to call initLogConstructor");return w.user}function z(){if(w.dev)return w.dev;throw Error("failed to call initLogConstructor");}function B(a,b,c,d,e){return x().assert(a,b,c,d,e,void 0,void 0,void 0,void 0,void 0,void 0)};function ia(){var a,b=Object.create(null);a&&Object.assign(b,a);return b}function F(a){return a||{}};function J(){var a=100;this.Xa=a;this.qa=this.Ca=0;this.ea=Object.create(null)}J.prototype.has=function(a){return!!this.ea[a]};J.prototype.get=function(a){var b=this.ea[a];if(b)return b.access=++this.qa,b.payload};J.prototype.put=function(a,b){this.has(a)||this.Ca++;this.ea[a]={payload:b,access:this.qa};if(!(this.Ca<=this.Xa)){z().warn("lru-cache","Trimming LRU cache");a=this.ea;var c=this.qa+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.Ca--)}};var ja=F({c:!0,v:!0,a:!0,ad:!0,action:!0}),ka,la,ma=/[?&]amp_js[^&]*/,na=/[?&]amp_gsa[^&]*/,oa=/[?&]amp_r[^&]*/,pa=/[?&]amp_kit[^&]*/,qa=/[?&]usqp[^&]*/;
function L(a){var b;ka||(ka=self.document.createElement("a"),la=self.UrlCache||(self.UrlCache=new J));var c=b?null:la,d=ka;if(c&&c.has(a))a=c.get(a);else{d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=
d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;c&&c.put(a,e);a=e}return a}function ra(a){var b=[],c;for(c in a){var d=a[c];if(null!=d)if(Array.isArray(d))for(var e=0;e<d.length;e++){var f=d[e];b.push(encodeURIComponent(c)+"="+encodeURIComponent(f))}else e=d,b.push(encodeURIComponent(c)+"="+encodeURIComponent(e))}return b.join("&")}
function M(a,b){var c=void 0===c?"source":c;B(null!=a,"%s %s must be available",b,c);var d=a;a=d;"string"==typeof a&&(a=L(a));var e;(e="https:"==a.protocol||"localhost"==a.hostname||"127.0.0.1"==a.hostname)||(a=a.hostname,e=a.length-10,e=0<=e&&a.indexOf(".localhost",e)==e);B(e||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d)}function N(a){var b=a.indexOf("#");return-1==b?a:a.substring(0,b)}
function O(a){"string"==typeof a&&(a=L(a));return ha.cdnProxyRegex.test(a.origin)}
function sa(a){"string"==typeof a&&(a=L(a));if(!O(a))return a.href;var b=a.pathname.split("/");B(ja[b[1]],"Unknown path prefix in url %s",a.href);var c=b[2],d="s"==c?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(c);B(0<d.indexOf("."),"Expected a . in origin %s",d);b.splice(1,"s"==c?3:2);b=d+b.join("/");d=(d=a.search)&&"?"!=d?(d=d.replace(ma,"").replace(na,"").replace(oa,"").replace(pa,"").replace(qa,"").replace(/^[?&]/,""))?"?"+d:"":"";return b+d+(a.hash||"")};function P(a,b){if(a.__AMP__EXPERIMENT_TOGGLES)var c=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);c=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var d in a.AMP_CONFIG){var e=a.AMP_CONFIG[d];"number"===typeof e&&0<=e&&1>=e&&(c[d]=Math.random()<e)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(d=a.AMP_CONFIG["allow-doc-opt-in"],e=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){e=
e.getAttribute("content").split(",");for(var f=0;f<e.length;f++)-1!=d.indexOf(e[f])&&(c[e[f]]=!0)}Object.assign(c,ta(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length)for(d=a.AMP_CONFIG["allow-url-opt-in"],a=q(a.location.originalHash||a.location.hash),e=0;e<d.length;e++)f=a["e-"+d[e]],"1"==f&&(c[d[e]]=!0),"0"==f&&(c[d[e]]=!1)}var g=c;return!!g[b]}
function ta(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(e){z().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var d=0;d<c.length;d++)0!=c[d].length&&("-"==c[d][0]?a[c[d].substr(1)]=!1:a[c[d]]=!0);return a};function ua(a,b){var c=a.ownerDocument.defaultView,d=c.__AMP_TOP||(c.__AMP_TOP=c),e=c!=d,f=P(d,"ampdoc-fie");e&&!f?b=Q(c,b)?S(c,b):null:(a=T(a),a=U(a),b=Q(a,b)?S(a,b):null);return b}function V(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return S(a,b)}function va(a){a=a.__AMP_TOP||(a.__AMP_TOP=a);return Q(a,"performance")?S(a,"performance"):null}function wa(a,b){var c=T(a);c=U(c);return S(c,b)}function T(a){return a.nodeType?V((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}
function U(a){a=T(a);return a.isSingleDoc()?a.win:a}function S(a,b){Q(a,b);var c=xa(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function ya(a,b){var c=za(a,b);if(c)return c;a=xa(a);a[b]=Aa();return a[b].promise}function za(a,b){var c=xa(a)[b];if(c){if(c.promise)return c.promise;S(a,b);return c.promise=Promise.resolve(c.obj)}return null}function xa(a){var b=a.services;b||(b=a.services={});return b}
function Q(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)}function Aa(){var a=new m,b=a,c=b.promise,d=b.resolve;b=b.reject;c.catch(function(){});return{obj:null,promise:c,resolve:d,reject:b,context:null,ctor:null}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var Ba=/(\0)|^(-)$|([\x01-\x1f\x7f]|^-?[0-9])|([\x80-\uffff0-9a-zA-Z_-]+)|[^]/g;function Ca(a,b,c,d,e){return e?e:b?"\ufffd":d?a.slice(0,-1)+"\\"+a.slice(-1).charCodeAt(0).toString(16)+" ":"\\"+a};function Da(a,b,c){try{var d=a.open(b,"_blank",c)}catch(e){z().error("DOM","Failed to open url on target: ","_blank",e)}d||(d=a.open(b,"_top"));return d}function Ea(a){return"SCRIPT"==a.tagName&&a.hasAttribute("type")&&"APPLICATION/JSON"==a.getAttribute("type").toUpperCase()};function Fa(a){var b=za(U(a),"amp-analytics-instrumentation");if(b)return b;var c=T(a);return c.waitForBodyOpen().then(function(){var a=c.win;var b=c.win.document.head;if(b){var f=[];b=b.querySelectorAll("script[custom-element]");for(var g=0;g<b.length;g++)f.push(b[g].getAttribute("custom-element"))}else f=[];a=f.includes("amp-analytics")?V(a,"extensions").waitForExtension(a,"amp-analytics"):Promise.resolve();return a}).then(function(){var b=c.win;return b.__AMP_EXTENDED_ELEMENTS&&b.__AMP_EXTENDED_ELEMENTS["amp-analytics"]?
ya(U(a),"amp-analytics-instrumentation"):null})};function W(a){return V(a,"timer")}function X(a){return wa(a,"viewer")};function Y(a,b,c){this.ampdoc=a;this.C=c;this.da=B(b.authorization,'"authorization" URL must be specified');M(this.da,'"authorization"');this.X=!b.noPingback;this.na=b.pingback;this.X&&(B(this.na,'"pingback" URL must be specified'),M(this.na,'"pingback"'));c=b;c.authorizationTimeout?(c=c.authorizationTimeout,B("number"==typeof c,'"authorizationTimeout" must be a number'),da().development||(c=Math.min(c,3E3))):c=3E3;this.sa=c;this.R=V(a.win,"xhr");this.B=W(a.win)}h=Y.prototype;
h.getConfig=function(){return{authorizationUrl:this.da,pingbackEnabled:this.X,pingbackUrl:this.na,authorizationTimeout:this.sa}};h.getAuthorizationUrl=function(){return this.da};h.isAuthorizationEnabled=function(){return!0};h.getAuthorizationTimeout=function(){return this.sa};h.authorize=function(){var a=this,b=this.C.buildUrl(this.da,!1);return b.then(function(b){return a.B.timeoutPromise(a.sa,a.R.fetchJson(b,{credentials:"include"})).then(function(a){return a.json()})})};h.isPingbackEnabled=function(){return this.X};
h.pingback=function(){var a=this;return this.C.buildUrl(this.na,!0).then(function(b){return a.R.sendSignal(b,{method:"POST",credentials:"include",headers:F({"Content-Type":"application/x-www-form-urlencoded"}),body:""})})};h.postAction=function(){};function Ga(a,b,c){this.Wa=a;this.Da=b;this.m=c;this.O=this.Ea=null;this.La=this.cb.bind(this);this.ib=0;this.Ha={}}h=Ga.prototype;h.connect=function(a){if(this.O)throw Error("already connected");this.O=a;this.Wa.addEventListener("message",this.La)};h.disconnect=function(){this.O&&(this.O=null,this.Wa.removeEventListener("message",this.La))};h.isConnected=function(){return null!=this.m};h.getTarget=function(){var a=Ha(this);if(!a)throw Error("not connected");return a};
function Ha(a){a.O&&!a.Ea&&(a.Ea="function"==typeof a.Da?a.Da():a.Da);return a.Ea}h.getTargetOrigin=function(){if(null==this.m)throw Error("not connected");return this.m};h.sendCommand=function(a,b){Ia(this,void 0,a,b)};h.sendCommandRsvp=function(a,b){var c=String(++this.ib),d=null,e=new Promise(function(a){d=a});this.Ha[c]={promise:e,resolver:d};Ia(this,c,a,b);return e};
function Ia(a,b,c,d){var e=a.getTarget();a="connect"==c?null!=a.m?a.m:"*":a.getTargetOrigin();e.postMessage({sentinel:"__AMP__",_rsvp:b,cmd:c,payload:d||null},a)}
h.cb=function(a){var b=this,c=a.data;if(c&&"__AMP__"==c.sentinel){var d=a.origin,e=c.cmd,f=c.payload||null;null==this.m&&"start"==e&&(this.m=d);null==this.m&&a.source&&Ha(this)==a.source&&(this.m=d);if(d==this.m){var g=c._rsvp,k=!!g&&"rsvp"!=e;a=this.va(g,e,f);k&&Promise.resolve(a).then(function(a){Ia(b,g,"rsvp",{result:a})},function(a){Ia(b,g,"rsvp",{error:String(a)})})}}};
h.va=function(a,b,c){if("rsvp"==b){var d=a&&this.Ha[a];d&&("error"in c?d.resolver(Promise.reject(Error(c.error))):d.resolver(c.result),delete this.Ha[a])}else return this.O(b,c)};function Ja(a,b){if("."==b)return a;b=b.split(".");for(var c=0;c<b.length;c++){var d=b[c];if(d&&a&&void 0!==a[d]&&(null==a||"object"!=typeof a?0:Object.prototype.hasOwnProperty.call(a,d)))a=a[d];else{a=void 0;break}}return a}function Ka(a,b){try{return JSON.parse(a)}catch(c){return b&&b(c),null}};function La(a){var b=!1;void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function Ma(a,b,c){var d=this;this.ampdoc=a;this.C=c;this.Za=b;this.B=W(a.win);this.ja=B(b.iframeSrc,'"iframeSrc" URL must be specified');M(this.ja,'"iframeSrc"');(this.V=b.iframeVars||null)&&B(Array.isArray(this.V),'"iframeVars" must be an array');this.$a=B(b.defaultResponse,'"defaultResponse" must be specified');this.m=L(this.ja).origin;this.ta=this.fa=null;this.W=a.win.document.createElement("iframe");La(this.W);this.Z=new Ga(this.ampdoc.win,function(){return d.W.contentWindow},this.m);this.Na=
null}h=Ma.prototype;h.disconnect=function(){this.Z.disconnect();this.ampdoc.getBody().removeChild(this.W)};h.getConfig=function(){return{iframeSrc:this.ja,iframeVars:this.V}};h.isAuthorizationEnabled=function(){return!0};h.authorize=function(){return Promise.race([Na(this),Oa(this)])};h.isPingbackEnabled=function(){return!0};h.pingback=function(){var a=this;return this.connect().then(function(){return a.Z.sendCommandRsvp("pingback",{})})};h.postAction=function(){Pa(this,null)};
h.connect=function(){if(!this.ta){var a=new m;this.ta=a.promise;this.fa=a.resolve;this.Na=Qa(this);this.Z.connect(this.va.bind(this));this.ampdoc.getBody().appendChild(this.W);this.W.src=this.ja}return this.ta};function Qa(a){return new Promise(function(b){var c=JSON.parse(JSON.stringify(a.Za));if(a.V){var d=a.V.join("&"),e=a.C.collectUrlVars(d,!1);b(e.then(function(a){c.iframeVars=a;return c}))}else b(c)})}
function Na(a){var b=3E3*(da().development?2:1);return a.B.promise(b).then(function(){return Ra(a)||a.$a})}function Oa(a){return a.connect().then(function(){return a.Z.sendCommandRsvp("authorize",{})}).then(function(b){b&&Promise.resolve().then(function(){return Pa(a,b)});return b})}
function Ra(a){var b=a.ampdoc.win,c=b.sessionStorage||b.localStorage;if(!c)return null;try{var d=c.getItem("amp-access-iframe");if(!d)return null;var e=JSON.parse(d);return e.t+6048E5<a.ampdoc.win.Date.now()?null:e.d||null}catch(f){z().error("amp-access-iframe","failed to restore access response: ",f);try{c.removeItem("amp-access-iframe")}catch(g){}return null}}
function Pa(a,b){var c=a.ampdoc.win;if(c=c.sessionStorage||c.localStorage)try{b?c.setItem("amp-access-iframe",JSON.stringify(F({t:a.ampdoc.win.Date.now(),d:b}))):c.removeItem("amp-access-iframe")}catch(d){z().error("amp-access-iframe","failed to store access response: ",d)}}h.va=function(a){var b=this;"connect"==a&&this.Na.then(function(a){b.Z.sendCommandRsvp("start",{protocol:"amp-access",config:a}).then(function(){b.fa&&(b.fa(),b.fa=null)})})};function Sa(a,b,c){this.ampdoc=a;this.C=c;this.ra=b.authorizationFallbackResponse||null;this.G=O(a.win.location)}h=Sa.prototype;h.getConfig=function(){return{authorizationResponse:this.ra}};h.isAuthorizationEnabled=function(){return!!this.ra&&!this.G};h.authorize=function(){return Promise.resolve(this.ra)};h.isPingbackEnabled=function(){return!1};h.pingback=function(){return Promise.resolve()};h.postAction=function(){};var Ta=["GET","POST"];function Ua(a,b){var c=Object.assign({},b),d=b.body;if(d&&"function"==typeof d.getFormData){var e=b.body;c.headers["Content-Type"]="multipart/form-data;charset=utf-8";b=e.entries();d=[];for(var f=b.next();!f.done;f=b.next())d.push(f.value);c.body=d}return{input:a,init:c}}
function Va(a,b){B("[object Object]"===ea.call(a),"Object expected: %s",a);var c="document"==b;if(!c)return new Response(a.body,a.init);var d=ia(),e={status:200,statusText:"OK",getResponseHeader:function(a){return d[String(a).toLowerCase()]||null}};if(a.init){var f=a.init;Array.isArray(f.headers)&&f.headers.forEach(function(a){var b=a[0],c=a[1];d[String(b).toLowerCase()]=String(c)});f.status&&(e.status=parseInt(f.status,10));f.statusText&&(e.statusText=String(f.statusText))}return new Response(a.body?
String(a.body):"",e)}
function Wa(a,b,c,d){if(!b)return Promise.resolve();var e=X(b),f=d.prerenderSafe?Promise.resolve():e.whenFirstVisible(),g=O(c),k=e.hasCapability("xhrInterceptor"),l=d.bypassInterceptorForDev&&!1;if(g||!k||l)return f;var n=b.getRootNode().documentElement,C=n.hasAttribute("allow-xhr-interception");return C?f.then(function(){return e.isTrustedViewer()}).then(function(b){if(b||P(a,"untrusted-xhr-interception")){var f=F({originalRequest:Ua(c,d)});return e.sendMessageAwaitResponse("xhr",f).then(function(a){return Va(a,
d.responseType)})}}):f}function Xa(a,b,c){!1!==c.ampCors&&(c=L(b),c=q(c.search),B(!("__amp_source_origin"in c),"Source origin is not allowed in %s",b),a=L(sa(a.location.href)).origin,a=encodeURIComponent("__amp_source_origin")+"="+encodeURIComponent(a),a&&(b=b.split("#",2),c=b[0].split("?",2),a=c[0]+(c[1]?"?"+c[1]+"&"+a:"?"+a),b=a+=b[1]?"#"+b[1]:""));return b}
function Ya(a){var b="text/html";a=a||{};var c=a.method;void 0===c?c="GET":(c=c.toUpperCase(),Ta.includes(c));a.method=c;a.headers=a.headers||F({});b&&(a.headers.Accept=b);return a}function Za(a,b,c){c=c||{};var d=a.origin||L(a.location.href).origin;a=L(b).origin;d==a&&(c.headers=c.headers||{},c.headers["AMP-Same-Origin"]="true");return c}
function $a(a){return new Promise(function(b){if(a.ok)return b(a);b=a.status;var c=x().createError("HTTP error "+b);c.retriable=415==b||500<=b&&600>b;c.response=a;throw c;})};function ab(a,b,c){var d=Ya(c);d=Za(a,b,d);b=Xa(a,b,d);var e=V(a,"ampdoc");c=e.isSingleDoc()?e.getSingleDoc():null;d.responseType="document";return Wa(a,c,b,d).then(function(a){return a?a.text().then(function(a){return(new DOMParser).parseFromString(a,"text/html")}):bb(b,d).then(function(a){var b=a.xhr;return b.responseXML})})}
function bb(a,b){return new Promise(function(c,d){var e=new XMLHttpRequest;e.open(b.method||"GET",a,!0);e.withCredentials="include"==b.credentials;e.responseType="document";for(var f in b.headers)e.setRequestHeader(f,b.headers[f]);e.onreadystatechange=function(){if(!(2>e.readyState))if(100>e.status||599<e.status)e.onreadystatechange=null,d(x().createExpectedError("Unknown HTTP status "+e.status));else if(4==e.readyState){var a={status:e.status,statusText:e.statusText,headers:cb(e.getAllResponseHeaders())};
a=new Response("",a);a=$a(a).then(function(a){return{response:a,xhr:e}});c(a)}};e.onerror=function(){d(x().createExpectedError("Request failure"))};e.onabort=function(){d(x().createExpectedError("Request aborted"))};"POST"==b.method?e.send(b.body):e.send()})}function cb(a){var b=F({}),c=a.replace(/\r?\n[\t ]+/g," ");c.split(/\r?\n/).forEach(function(a){var c=a.split(":"),d=c.shift().trim();d&&(c=c.join(":").trim(),b[d]=c)});return b};function db(a,b,c){this.ampdoc=a;this.C=c;this.w=new Y(a,b,c);this.o=X(a);this.R=V(a.win,"xhr");this.B=W(a.win);this.P=V(a.win,"vsync");var d=a.getRootNode().querySelector('meta[name="i-amphtml-access-state"]');this.I=d?d.getAttribute("content"):null;var e=P(a.win,"amp-access-server");this.G=O(a.win.location)||e;var f=e?this.o.getParam("serverAccessService"):null;this.Ba=f||N(a.win.location.href)}h=db.prototype;h.getConfig=function(){return{client:this.w.getConfig(),proxy:this.G,serverState:this.I}};
h.isAuthorizationEnabled=function(){return!0};
h.authorize=function(){var a=this;return this.G&&this.I?this.C.collectUrlVars(this.w.getAuthorizationUrl(),!1).then(function(b){var c={},d;for(d in b)null!=b[d]&&(c[d]=String(b[d]));b=F({url:N(a.ampdoc.win.location.href),state:a.I,vars:c});return a.B.timeoutPromise(a.w.getAuthorizationTimeout(),ab(a.ampdoc.win,a.Ba,{method:"POST",body:"request="+encodeURIComponent(JSON.stringify(b)),headers:F({"Content-Type":"application/x-www-form-urlencoded"})}))}).then(function(b){var c=b.querySelector('script[id="amp-access-data"]').textContent,
d=JSON.parse(c);return a.Aa(b).then(function(){return d})}):this.w.authorize()};h.isPingbackEnabled=function(){return this.w.isPingbackEnabled()};h.pingback=function(){return this.w.pingback()};h.postAction=function(){};
h.Aa=function(a){var b=this,c=a.querySelectorAll("[i-amphtml-access-id]");return this.P.mutatePromise(function(){for(var a=0;a<c.length;a++){var e=c[a],f=e.getAttribute("i-amphtml-access-id"),g=b.ampdoc.getRootNode().querySelector('[i-amphtml-access-id="'+String(f).replace(Ba,Ca)+'"]');g?g.parentElement.replaceChild(b.ampdoc.win.document.importNode(e,!0),g):z().warn("amp-access-server","Section not found: ",f)}})};function eb(a){if("undefined"!==typeof TextDecoder)return(new TextDecoder("utf-8")).decode(a);for(var b=new Uint8Array(a.buffer||a),c=Array(b.length),d=0;d<b.length;d++)c[d]=String.fromCharCode(b[d]);var e=c.join("");return decodeURIComponent(escape(e))}function fb(a){for(var b=new Uint8Array(a.length),c=0;c<a.length;c++){var d=a.charCodeAt(c);b[c]=d}return b};var jb={"-":"+",_:"/",".":"="};function kb(a){var b=atob(a.replace(/[-_.]/g,function(a){return jb[a]}));return fb(b)};function lb(a){a=a.trim();a=a.replace(/^\-+BEGIN[^-]*\-+/,"");a=a.replace(/\-+END[^-]*\-+$/,"");a=a.replace(/[\r\n]/g,"").trim();return fb(atob(a))};function mb(a){this.win=a;this.pa=a.crypto&&(a.crypto.subtle||a.crypto.webkitSubtle)||null}mb.prototype.decode=function(a){return nb(a).payload};mb.prototype.isVerificationSupported=function(){return!!this.pa};
mb.prototype.decodeAndVerify=function(a,b){var c=this;if(!this.pa)throw Error("Crypto is not supported on this platform");var d=new Promise(function(b){return b(nb(a))});return d.then(function(a){var d=a.header.alg;if(!d||"RS256"!=d)throw Error("Only alg=RS256 is supported");return ob(c,b).then(function(b){var d=kb(a.sig);return c.pa.verify({name:"RSASSA-PKCS1-v1_5"},b,d,fb(a.verifiable))}).then(function(b){if(b)return a.payload;throw Error("Signature verification failed");})})};
function nb(a){function b(){throw Error('Invalid token: "'+a+'"');}var c=a.split(".");3!=c.length&&b();var d=kb(c[0]),e=kb(c[1]);return{header:Ka(eb(d),b),payload:Ka(eb(e),b),verifiable:c[0]+"."+c[1],sig:c[2]}}function ob(a,b){return b.then(function(b){return a.pa.importKey("spki",lb(b),{name:"RSASSA-PKCS1-v1_5",hash:{name:"SHA-256"}},!1,["verify"])})};function pb(a,b,c){this.ampdoc=a;this.C=c;this.w=new Y(a,b,c);this.o=X(a);this.R=V(a.win,"xhr");this.B=W(a.win);this.P=V(a.win,"vsync");this.I=(c=a.getRootNode().querySelector('meta[name="i-amphtml-access-state"]'))?c.getAttribute("content"):null;c=P(a.win,"amp-access-server-jwt");this.G=O(a.win.location)||c;this.Ba=(c?this.o.getParam("serverAccessService"):null)||N(a.win.location.href);this.Y=b.publicKey||null;this.M=b.publicKeyUrl||null;B(this.Y||this.M,'"publicKey" or "publicKeyUrl" must be specified');
this.M&&M(this.M,'"publicKeyUrl"');this.Y&&this.M&&x().warn("amp-access-server-jwt",'Both "publicKey" and "publicKeyUrl" specified. The "publicKeyUrl" will be ignored.');this.wa=new mb(a.win)}h=pb.prototype;h.getConfig=function(){return{client:this.w.getConfig(),proxy:this.G,serverState:this.I,publicKey:this.Y,publicKeyUrl:this.M}};h.isAuthorizationEnabled=function(){return!0};h.authorize=function(){return this.G&&this.I?qb(this):rb(this)};h.isPingbackEnabled=function(){return this.w.isPingbackEnabled()};
h.pingback=function(){return this.w.pingback()};h.postAction=function(){};
function sb(a){var b=a.C.buildUrl(a.w.getAuthorizationUrl(),!1).then(function(b){return a.B.timeoutPromise(3E3,a.R.fetchText(b,{credentials:"include"}))}).then(function(a){return a.text()}).then(function(b){var c=a.wa.decode(b);B(c.amp_authdata,'"amp_authdata" must be present in JWT');return{encoded:b,jwt:c}});da().development&&(a.wa.isVerificationSupported()?b=b.then(function(b){return a.wa.decodeAndVerify(b.encoded,tb(a)).then(function(){return b})}):x().warn("amp-access-server-jwt","Cannot verify signature on this browser since it doesn't support WebCrypto APIs"),
b=b.then(function(a){var b=a.jwt,c=Date.now(),f=b.exp;B(f,'"exp" field must be specified');B(1E3*parseFloat(f)>c,"token has expired: %s",f);b=b.aud;B(b,'"aud" field must be specified');c=!1;if(Array.isArray(b))for(f=0;f<b.length;f++){if("ampproject.org"==b[f]){c=!0;break}}else c="ampproject.org"==b;B(c,'"aud" must be "%s": %s',"ampproject.org",b);return a}));return b.catch(function(a){throw x().createError("JWT fetch or validation failed: ",a);})}
function tb(a){return a.Y?Promise.resolve(a.Y):a.R.fetchText(a.M).then(function(a){return a.text()})}function rb(a){return sb(a).then(function(a){return a.jwt.amp_authdata})}
function qb(a){return sb(a).then(function(b){var c=b.encoded,d=b.jwt.amp_authdata;b=ra(F({url:N(a.ampdoc.win.location.href),state:a.I,jwt:c}));return a.B.timeoutPromise(3E3,ab(a.ampdoc.win,a.Ba,{method:"POST",body:b,headers:F({"Content-Type":"application/x-www-form-urlencoded"})})).then(function(b){return a.Aa(b)}).then(function(){return d})})}
h.Aa=function(a){var b=this,c=a.querySelectorAll("[i-amphtml-access-id]");return this.P.mutatePromise(function(){for(var a=0;a<c.length;a++){var e=c[a],f=e.getAttribute("i-amphtml-access-id"),g=b.ampdoc.getRootNode().querySelector('[i-amphtml-access-id="'+String(f).replace(Ba,Ca)+'"]');g?g.parentElement.replaceChild(b.ampdoc.win.document.importNode(e,!0),g):z().warn("amp-access-server-jwt","Section not found: ",f)}})};function ub(a,b){this.ampdoc=a;this.Ua=B(b.vendor,'"vendor" name must be specified');this.mb=b[this.Ua]||{};this.X=!b.noPingback;a=new m;this.Va=a.promise;this.Ga=a.resolve}h=ub.prototype;h.getVendorName=function(){return this.Ua};h.getConfig=function(){return this.mb};h.registerVendor=function(a){B(this.Ga,"Vendor has already been registered");this.Ga(a);this.Ga=null};h.isAuthorizationEnabled=function(){return!0};h.authorize=function(){return this.Va.then(function(a){return a.authorize()})};
h.isPingbackEnabled=function(){return this.X};h.pingback=function(){return this.Va.then(function(a){return a.pingback()})};h.postAction=function(){};var Z;function vb(a,b,c){var d=void 0,e=a,f=c;var g=function(a){try{return f(a)}catch(C){throw self.reportError(C),C;}};var k=wb(),l=!1;d&&(l=d.capture);e.addEventListener(b,g,k?d:l);return function(){e&&e.removeEventListener(b,g,k?d:l);g=e=f=null}}function wb(){if(void 0!==Z)return Z;Z=!1;try{var a={get capture(){Z=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return Z};function xb(a,b){return vb(a,"message",b)}function yb(a,b){var c=b,d=vb(a,"click",function(a){try{c(a)}finally{c=null,d()}});return d};var zb=/RETURN_URL/;function Ab(a,b){var c=X(a),d=parseInt(c.getParam("dialog"),10);return d?new Bb(c,b):new Cb(a.win,c,b)}function Db(a,b){return Ab(a,b).open()}function Bb(a,b){this.viewer=a;this.urlOrPromise=b}Bb.prototype.getLoginUrl=function(){return("string"==typeof this.urlOrPromise?Promise.resolve(this.urlOrPromise):this.urlOrPromise).then(function(a){return Eb(a,"RETURN_URL")})};
Bb.prototype.open=function(){var a=this;return this.getLoginUrl().then(function(b){return a.viewer.sendMessageAwaitResponse("openDialog",F({url:b}))})};function Cb(a,b,c){this.win=a;this.viewer=b;this.urlOrPromise=c;this.la=this.L=this.T=this.A=this.za=this.aa=null}Cb.prototype.open=function(){var a=this;B(!this.aa,"Dialog already opened");return(new Promise(function(b,c){a.aa=b;a.za=c;Fb(a)})).then(function(b){Gb(a);return b},function(b){Gb(a);throw b;})};
function Gb(a){a.aa=null;a.za=null;if(a.A){try{a.A.close()}catch(b){}a.A=null}a.L&&(a.win.clearInterval(a.L),a.L=null);a.la&&(a.la(),a.la=null)}Cb.prototype.getLoginUrl=function(){var a=this;return("string"==typeof this.urlOrPromise?Promise.resolve(this.urlOrPromise):this.urlOrPromise).then(function(b){return Eb(b,Hb(a))})};
function Fb(a){var b=a.win.screen,c=Math.floor(Math.min(700,.9*b.width)),d=Math.floor(Math.min(450,.9*b.height)),e="height="+d+",width="+c+",left="+Math.floor((b.width-c)/2)+",top="+Math.floor((b.height-d)/2);b=e+",resizable=yes,scrollbars=yes";var f=Hb(a);a.T=null;"string"==typeof a.urlOrPromise?(c=Eb(a.urlOrPromise,f),a.A=Da(a.win,c,b),a.A&&(a.T=Promise.resolve())):(a.A=Da(a.win,"",b),a.A&&(a.T=a.urlOrPromise.then(function(b){b=Eb(b,f);a.A.location.replace(b)},function(a){throw Error("failed to resolve url: "+
a);})));a.T?a.T.then(function(){Ib(a,f)},function(b){Jb(a,null,b)}):Jb(a,null,Error("failed to open dialog"))}function Ib(a,b){var c=L(b).origin;a.L=a.win.setInterval(function(){a.A.closed&&(a.win.clearInterval(a.L),a.L=null,a.win.setTimeout(function(){Jb(a,"")},3E3))},500);a.la=xb(a.win,function(b){b.origin==c&&b.data&&"amp"==b.data.sentinel&&"result"==b.data.type&&(a.A&&a.A.postMessage(F({sentinel:"amp",type:"result-ack"}),c),Jb(a,b.data.result))})}
function Jb(a,b,c){a.aa&&(c?a.za(c):a.aa(b),Gb(a))}function Hb(a){var b=a.viewer.getResolvedViewerUrl();return ha.cdn+"/v0/amp-login-done-0.1.html?url="+encodeURIComponent(b)}function Eb(a,b){return zb.test(a)?a.replace(zb,encodeURIComponent(b)):a+(-1==a.indexOf("?")?"?":"&")+"return="+encodeURIComponent(b)};function Kb(a,b){var c;Fa(a).then(function(d){d&&d.triggerEventForTarget(a,b,c)})};var Lb={CLIENT:"client",IFRAME:"iframe",SERVER:"server",VENDOR:"vendor",OTHER:"other"};
function Mb(a,b,c,d,e,f){this.ampdoc=a;this.ha=c;this.oa=d;this.xa=e;this.F=f;this.Oa=P(a.win,"amp-access-server");this.eb=P(a.win,"amp-access-jwt");var g=b.type?x().assertEnumValue(Lb,b.type,"access type"):null;g||(g=b.vendor?"vendor":"client");"server"!=g||this.Oa||(x().warn("amp-access",'Experiment "amp-access-server" is not enabled.'),g="client");"client"==g&&this.Oa&&(x().info("amp-access","Forcing access type: SERVER"),g="server");"iframe"!=g||P(this.ampdoc.win,"amp-access-iframe")||(x().error("amp-access",
'Experiment "amp-access-iframe" is not enabled.'),g="client");this.Fa=g;g=b.login;var k={};if(g)if("string"==typeof g)k[""]=g;else if("[object Object]"===ea.call(g))for(var l in g)k[l]=g[l];else B(!1,'"login" must be either a single URL or a map of URLs');for(var n in k)M(k[n],this.F);this.ka=k;this.Ka=b.authorizationFallbackResponse;this.fb=b.namespace||null;this.K=Nb(this,b);this.Ta=ua(f,"url-replace");this.hb=Db.bind(null,a);this.ca=null;a=new m;this.ab=a.promise;this.ua=a.resolve;this.Qa={};this.H=
null;this.Pa=0}h=Mb.prototype;h.getNamespace=function(){return this.fb};h.getType=function(){return this.Fa};h.getAdapter=function(){return this.K};h.getAuthResponse=function(){return this.ca};
function Nb(a,b){var c={buildUrl:a.buildUrl.bind(a),collectUrlVars:a.collectUrlVars.bind(a)},d=a.eb&&!0===b.jwt;switch(a.Fa){case "client":return d?new pb(a.ampdoc,b,c):new Y(a.ampdoc,b,c);case "iframe":return new Ma(a.ampdoc,b,c);case "server":return d?new pb(a.ampdoc,b,c):new db(a.ampdoc,b,c);case "vendor":return new ub(a.ampdoc,b);case "other":return new Sa(a.ampdoc,b,c)}throw z().createError("Unsupported access type: ",a.Fa);}h.getAdapterConfig=function(){return this.K.getConfig()};
h.whenFirstAuthorized=function(){return this.ab};h.ia=function(){var a=this.ampdoc.getRootNode();return a.documentElement||a.body||a};h.D=function(a){Kb(this.ia(),a)};h.start=function(){Ob(this)};h.buildUrl=function(a,b){var c=this;return Pb(this,b).then(function(b){return c.Ta.expandUrlAsync(a,b)})};h.collectUrlVars=function(a,b){var c=this;return Pb(this,b).then(function(b){return c.Ta.collectVars(a,b)})};
function Pb(a,b){return a.ha().then(function(c){var d={READER_ID:c,ACCESS_READER_ID:c};b&&(d.AUTHDATA=function(b){if(a.ca)return Ja(a.ca,b)});return d})}
h.runAuthorization=function(a){var b=this;if(!this.K.isAuthorizationEnabled())return this.ua(),Promise.resolve();var c=this.K.authorize().catch(function(c){b.D("access-authorization-failed");if(b.Ka&&!a)return x().error("amp-access","Authorization failed: ",c),b.Ka;throw c;});return c.then(function(a){b.ca=a;b.ua();Ob(b);return a}).catch(function(a){x().error("amp-access","Authorization failed: ",a);b.ua();throw a;})};
h.reportViewToServer=function(){var a=this;return this.K.pingback().then(function(){a.D("access-pingback-sent")}).catch(function(b){a.D("access-pingback-failed");throw x().createError("Pingback failed: ",b);})};h.getLoginUrl=function(a){return Ab(this.ampdoc,a).getLoginUrl()};h.loginWithType=function(a){B(this.ka[a],"Login URL is not configured: %s",a);var b=B(this.Qa[a],"Login URL is not ready: %s",a);return Qb(this,b,a)};h.loginWithUrl=function(a,b){b=void 0===b?"":b;return Qb(this,a,b)};
function Qb(a,b,c){var d=Date.now();if(a.H&&1E3>d-a.Pa)return a.H;Rb(a,c,"started");var e=a.hb(b),f=e.then(function(b){a.H=null;b=q(b).success;var d="true"==b||"yes"==b||"1"==b;d?Rb(a,c,"success"):Rb(a,c,"rejected");if(d||!b){a.K.postAction();var e=a.runAuthorization(!0);a.xa(e);return e.then(function(){a.oa(0)})}}).catch(function(b){Rb(a,c,"failed");a.H==f&&(a.H=null);throw b;});a.H=f;a.Pa=d;return a.H}function Rb(a,b,c){a.D("access-login-"+c);b&&a.D("access-login-"+b+"-"+c)}
function Ob(a){if(0!=Object.keys(a.ka).length){var b=[],c={},d;for(d in a.ka)c.S=d,b.push(a.buildUrl(a.ka[c.S],!0).then(function(b){return function(c){a.Qa[b.S]=c;return{type:b.S,url:c}}}(c))),c={S:c.S};Promise.all(b)}};function Sb(){this.l=null}h=Sb.prototype;h.add=function(a){var b=this;this.l||(this.l=[]);this.l.push(a);return function(){b.remove(a)}};h.remove=function(a){this.l&&(a=this.l.indexOf(a),-1<a&&this.l.splice(a,1))};h.removeAll=function(){this.l&&(this.l.length=0)};h.fire=function(a){if(this.l)for(var b=this.l,c=0;c<b.length;c++)(0,b[c])(a)};h.getHandlerCount=function(){return this.l?this.l.length:0};function Tb(a,b){var c="\n/*# sourceURL=/extensions/amp-access/0.1/amp-access.css*/",d=!1,e="amp-access",f=a.getHeadNode(),g=Ub(f,Vb(f,c),d||!1,e||null);if(b){var k=a.getRootNode();if(Wb(k,g))b(g);else var l=setInterval(function(){Wb(k,g)&&(clearInterval(l),b(g))},4)}}
function Ub(a,b,c,d){var e=a.__AMP_CSS_SM;e||(e=a.__AMP_CSS_SM=ia());var f=!c&&d&&"amp-custom"!=d&&"amp-keyframes"!=d,g=c?"amp-runtime":f?"amp-extension="+d:null;if(g){var k=Xb(a,e,g);if(k)return k.textContent!==b&&(k.textContent=b),k}var l=(a.ownerDocument||a).createElement("style");l.textContent=b;var n=null;c?l.setAttribute("amp-runtime",""):f?(l.setAttribute("amp-extension",d||""),n=Xb(a,e,"amp-runtime")):(d&&l.setAttribute(d,""),n=a.lastChild);b=n;a.insertBefore(l,b?b.nextSibling:a.firstChild);
g&&(e[g]=l);return l}function Xb(a,b,c){return b[c]?b[c]:(a=a.querySelector("style["+c+"]"))?b[c]=a:null}function Vb(a,b){return(a=a.__AMP_CSS_TR)?a(b):b}function Wb(a,b){var c=a.styleSheets;for(a=0;a<c.length;a++){var d=c[a];if(d.ownerNode==b)return!0}return!1};self.AMPErrors=self.AMPErrors||[];var Yb=function(){function a(a,b,c,d){c=c||{};for(d=a.length;d--;c[a[d]]=b);return c}function b(){this.yy={}}var c=[1,3],d=[1,4],e=[1,18],f=[1,19],g=[1,14],k=[1,15],l=[1,16],n=[1,17],C=[1,21],R=[1,22],r=[5,6,7,10],y=[5,6,7,10,15,16,17,18,19,20,21],E=[5,6,7,10,15,16,17,18,19,20,21,25,27],I={trace:function(){},yy:{},kb:{error:2,result:3,search_condition:4,EOF:5,OR:6,AND:7,NOT:8,"(":9,")":10,predicate:11,comparison_predicate:12,truthy_predicate:13,scalar_exp:14,EQ:15,DEQ:16,NEQ:17,LT:18,LTE:19,GT:20,
GTE:21,atom:22,field_ref:23,literal:24,DOT:25,field_name:26,"[":27,string:28,"]":29,NAME:30,STRING:31,NUMERIC:32,TRUE:33,FALSE:34,NULL:35,$accept:0,$end:1},ba:{2:"error",5:"EOF",6:"OR",7:"AND",8:"NOT",9:"(",10:")",15:"EQ",16:"DEQ",17:"NEQ",18:"LT",19:"LTE",20:"GT",21:"GTE",25:"DOT",27:"[",29:"]",30:"NAME",31:"STRING",32:"NUMERIC",33:"TRUE",34:"FALSE",35:"NULL"},Ra:[0,[3,2],[4,3],[4,3],[4,2],[4,3],[4,1],[11,1],[11,1],[12,3],[12,3],[12,3],[12,3],[12,3],[12,3],[12,3],[13,1],[14,1],[14,1],[22,1],[23,
3],[23,4],[23,1],[26,1],[28,1],[24,1],[24,1],[24,1],[24,1],[24,1]],performAction:function(a,b,c,d,e,f){var g=f.length-1;switch(e){case 1:return f[g-1];case 2:this.h=f[g-2]||f[g];break;case 3:this.h=f[g-2]&&f[g];break;case 4:this.h=!f[g];break;case 5:this.h=f[g-1];break;case 6:case 7:case 8:case 17:case 18:case 19:this.h=f[g];break;case 9:this.h=f[g-2]===f[g];break;case 10:throw Error('"==" is not allowed, use "="');case 11:this.h=f[g-2]!==f[g];break;case 12:this.h=typeof f[g-2]==typeof f[g]&&f[g-
2]<f[g];break;case 13:this.h=typeof f[g-2]==typeof f[g]&&f[g-2]<=f[g];break;case 14:this.h=typeof f[g-2]==typeof f[g]&&f[g-2]>f[g];break;case 15:this.h=typeof f[g-2]==typeof f[g]&&f[g-2]>=f[g];break;case 16:this.h=void 0!==f[g]&&null!==f[g]&&""!==f[g]&&0!==f[g]&&!1!==f[g];break;case 20:this.h="[object Object]"==Object.prototype.toString.call(f[g-2])&&f[g-2].hasOwnProperty(f[g])?f[g-2][f[g]]:null;break;case 21:this.h="[object Object]"==Object.prototype.toString.call(f[g-3])&&f[g-3].hasOwnProperty(f[g-
1])?f[g-3][f[g-1]]:null;break;case 22:this.h=void 0!==d[f[g]]?d[f[g]]:null;break;case 23:this.h=a;break;case 24:this.h=a.substring(1,a.length-1);break;case 26:this.h=Number(a);break;case 27:this.h=!0;break;case 28:this.h=!1;break;case 29:this.h=null}},table:[{3:1,4:2,8:c,9:d,11:5,12:6,13:7,14:8,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:k,34:l,35:n},{1:[3]},{5:[1,20],6:C,7:R},{4:23,8:c,9:d,11:5,12:6,13:7,14:8,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:k,34:l,35:n},{4:24,8:c,9:d,11:5,12:6,
13:7,14:8,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:k,34:l,35:n},a(r,[2,6]),a(r,[2,7]),a(r,[2,8]),a(r,[2,16],{15:[1,25],16:[1,26],17:[1,27],18:[1,28],19:[1,29],20:[1,30],21:[1,31]}),a(y,[2,17]),a(y,[2,18],{25:[1,32],27:[1,33]}),a(y,[2,19]),a(E,[2,22]),a(y,[2,25]),a(y,[2,26]),a(y,[2,27]),a(y,[2,28]),a(y,[2,29]),a(E,[2,23]),a([5,6,7,10,15,16,17,18,19,20,21,29],[2,24]),{1:[2,1]},{4:34,8:c,9:d,11:5,12:6,13:7,14:8,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:k,34:l,35:n},{4:35,8:c,9:d,11:5,12:6,
13:7,14:8,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:k,34:l,35:n},a(r,[2,4]),{6:C,7:R,10:[1,36]},{14:37,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:k,34:l,35:n},{14:38,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:k,34:l,35:n},{14:39,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:k,34:l,35:n},{14:40,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:k,34:l,35:n},{14:41,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:k,34:l,35:n},{14:42,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:k,34:l,35:n},
{14:43,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:k,34:l,35:n},{26:44,30:e},{28:45,31:f},a([5,6,10],[2,2],{7:R}),a(r,[2,3]),a(r,[2,5]),a(r,[2,9]),a(r,[2,10]),a(r,[2,11]),a(r,[2,12]),a(r,[2,13]),a(r,[2,14]),a(r,[2,15]),a(E,[2,20]),{29:[1,46]},a(E,[2,21])],defaultActions:{20:[2,1]},parseError:function(a,b){if(b.recoverable)this.trace(a);else throw a=Error(a),a.hash=b,a;},parse:function(a){function b(){var a=p.lex()||y;"number"!==typeof a&&(a=c.kb[a]||a);return a}var c=this,d=[0],e=[null],f=[],g=
this.table,gb="",k=0,l=0,n=0,r=2,y=1,C=f.slice.call(arguments,1),p=Object.create(this.lexer),G={yy:{}};for(A in this.yy)Object.prototype.hasOwnProperty.call(this.yy,A)&&(G.yy[A]=this.yy[A]);p.setInput(a,G.yy);G.yy.lexer=p;G.yy.parser=this;"undefined"==typeof p.yylloc&&(p.yylloc={});var E=p.yylloc;f.push(E);var R=p.options&&p.options.ranges;this.parseError="function"===typeof G.yy.parseError?G.yy.parseError:Object.getPrototypeOf(this).parseError;for(var t,I,H,v,K={},fa,D,hb;;){H=d[d.length-1];if(this.defaultActions[H])v=
this.defaultActions[H];else{if(null===t||"undefined"==typeof t)t=b();v=g[H]&&g[H][t]}if("undefined"===typeof v||!v.length||!v[0]){var ib="";var A=[];for(fa in g[H])this.ba[fa]&&fa>r&&A.push("'"+this.ba[fa]+"'");ib=p.showPosition?"Parse error on line "+(k+1)+":\n"+p.showPosition()+"\nExpecting "+A.join(", ")+", got '"+(this.ba[t]||t)+"'":"Parse error on line "+(k+1)+": Unexpected "+(t==y?"end of input":"'"+(this.ba[t]||t)+"'");this.parseError(ib,{text:p.match,token:this.ba[t]||t,line:p.yylineno,loc:E,
expected:A})}if(v[0]instanceof Array&&1<v.length)throw Error("Parse Error: multiple actions possible at state: "+H+", token: "+t);switch(v[0]){case 1:d.push(t);e.push(p.yytext);f.push(p.yylloc);d.push(v[1]);t=null;I?(t=I,I=null):(l=p.yyleng,gb=p.yytext,k=p.yylineno,E=p.yylloc,0<n&&n--);break;case 2:D=this.Ra[v[1]][1];K.h=e[e.length-D];K.Ia={first_line:f[f.length-(D||1)].first_line,last_line:f[f.length-1].last_line,first_column:f[f.length-(D||1)].first_column,last_column:f[f.length-1].last_column};
R&&(K.Ia.range=[f[f.length-(D||1)].range[0],f[f.length-1].range[1]]);A=this.performAction.apply(K,[gb,l,k,G.yy,v[1],e,f].concat(C));if("undefined"!==typeof A)return A;D&&(d=d.slice(0,-2*D),e=e.slice(0,-1*D),f=f.slice(0,-1*D));d.push(this.Ra[v[1]][0]);e.push(K.h);f.push(K.Ia);hb=g[d[d.length-2]][d[d.length-1]];d.push(hb);break;case 3:return!0}}}},fc=function(){return{EOF:1,parseError:function(a,b){if(this.yy.parser)this.yy.parser.parseError(a,b);else throw Error(a);},setInput:function(a,b){this.yy=
b||this.yy||{};this._input=a;this._more=this._backtrack=this.done=!1;this.yylineno=this.yyleng=0;this.yytext=this.matched=this.match="";this.conditionStack=["INITIAL"];this.yylloc={first_line:1,first_column:0,last_line:1,last_column:0};this.options.ranges&&(this.yylloc.range=[0,0]);this.offset=0;return this},input:function(){var a=this._input[0];this.yytext+=a;this.yyleng++;this.offset++;this.match+=a;this.matched+=a;var b=a.match(/(?:\r\n?|\n).*/g);b?(this.yylineno++,this.yylloc.last_line++):this.yylloc.last_column++;
this.options.ranges&&this.yylloc.range[1]++;this._input=this._input.slice(1);return a},unput:function(a){var b=a.length,c=a.split(/(?:\r\n?|\n)/g);this._input=a+this._input;this.yytext=this.yytext.substr(0,this.yytext.length-b);this.offset-=b;var d=this.match.split(/(?:\r\n?|\n)/g);this.match=this.match.substr(0,this.match.length-1);this.matched=this.matched.substr(0,this.matched.length-1);c.length-1&&(this.yylineno-=c.length-1);a=this.yylloc.range;this.yylloc={first_line:this.yylloc.first_line,last_line:this.yylineno+
1,first_column:this.yylloc.first_column,last_column:c?(c.length===d.length?this.yylloc.first_column:0)+d[d.length-c.length].length-c[0].length:this.yylloc.first_column-b};this.options.ranges&&(this.yylloc.range=[a[0],a[0]+this.yyleng-b]);this.yyleng=this.yytext.length;return this},more:function(){this._more=!0;return this},reject:function(){if(this.options.backtrack_lexer)this._backtrack=!0;else return this.parseError("Lexical error on line "+(this.yylineno+1)+". You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n"+
this.showPosition(),{text:"",token:null,line:this.yylineno});return this},less:function(a){this.unput(this.match.slice(a))},pastInput:function(){var a=this.matched.substr(0,this.matched.length-this.match.length);return(20<a.length?"...":"")+a.substr(-20).replace(/\n/g,"")},upcomingInput:function(){var a=this.match;20>a.length&&(a+=this._input.substr(0,20-a.length));return(a.substr(0,20)+(20<a.length?"...":"")).replace(/\n/g,"")},showPosition:function(){var a=this.pastInput(),b=Array(a.length+1).join("-");
return a+this.upcomingInput()+"\n"+b+"^"},test_match:function(a,b){var c;if(this.options.backtrack_lexer){var d={yylineno:this.yylineno,yylloc:{first_line:this.yylloc.first_line,last_line:this.last_line,first_column:this.yylloc.first_column,last_column:this.yylloc.last_column},yytext:this.yytext,match:this.match,matches:this.matches,matched:this.matched,yyleng:this.yyleng,offset:this.offset,_more:this._more,_input:this._input,yy:this.yy,conditionStack:this.conditionStack.slice(0),done:this.done};
this.options.ranges&&(d.yylloc.range=this.yylloc.range.slice(0))}if(c=a[0].match(/(?:\r\n?|\n).*/g))this.yylineno+=c.length;this.yylloc={first_line:this.yylloc.last_line,last_line:this.yylineno+1,first_column:this.yylloc.last_column,last_column:c?c[c.length-1].length-c[c.length-1].match(/\r?\n?/)[0].length:this.yylloc.last_column+a[0].length};this.yytext+=a[0];this.match+=a[0];this.matches=a;this.yyleng=this.yytext.length;this.options.ranges&&(this.yylloc.range=[this.offset,this.offset+=this.yyleng]);
this._backtrack=this._more=!1;this._input=this._input.slice(a[0].length);this.matched+=a[0];a=this.performAction.call(this,this.yy,this,b,this.conditionStack[this.conditionStack.length-1]);this.done&&this._input&&(this.done=!1);if(a)return a;if(this._backtrack)for(var e in d)this[e]=d[e];return!1},next:function(){if(this.done)return this.EOF;this._input||(this.done=!0);var a;this._more||(this.match=this.yytext="");for(var b=this._currentRules(),c=0;c<b.length;c++)if((a=this._input.match(this.rules[b[c]]))&&
(!d||a[0].length>d[0].length)){var d=a;var e=c;if(this.options.backtrack_lexer){d=this.test_match(a,b[c]);if(!1!==d)return d;if(this._backtrack)d=!1;else return!1}else if(!this.options.flex)break}return d?(d=this.test_match(d,b[e]),!1!==d?d:!1):""===this._input?this.EOF:this.parseError("Lexical error on line "+(this.yylineno+1)+". Unrecognized text.\n"+this.showPosition(),{text:"",token:null,line:this.yylineno})},lex:function(){var a=this.next();return a?a:this.lex()},begin:function(a){this.conditionStack.push(a)},
popState:function(){return 0<this.conditionStack.length-1?this.conditionStack.pop():this.conditionStack[0]},_currentRules:function(){return this.conditionStack.length&&this.conditionStack[this.conditionStack.length-1]?this.conditions[this.conditionStack[this.conditionStack.length-1]].rules:this.conditions.INITIAL.rules},topState:function(a){a=this.conditionStack.length-1-Math.abs(a||0);return 0<=a?this.conditionStack[a]:"INITIAL"},pushState:function(a){this.begin(a)},stateStackSize:function(){return this.conditionStack.length},
options:{},performAction:function(a,b,c){switch(c){case 1:return 7;case 2:return 6;case 3:return 8;case 4:return 35;case 5:return 33;case 6:return 33;case 7:return 34;case 8:return 34;case 9:return 9;case 10:return 10;case 11:return 27;case 12:return 29;case 13:return"|";case 14:return 19;case 15:return 18;case 16:return 21;case 17:return 20;case 18:return 17;case 19:return 16;case 20:return 15;case 21:return 32;case 22:return 30;case 23:return 31;case 24:return 31;case 25:return 25;case 26:return"INVALID";
case 27:return 5}},rules:[/^(?:\s+)/,/^(?:AND\b)/,/^(?:OR\b)/,/^(?:NOT\b)/,/^(?:NULL\b)/,/^(?:TRUE\b)/,/^(?:true\b)/,/^(?:FALSE\b)/,/^(?:false\b)/,/^(?:\()/,/^(?:\))/,/^(?:\[)/,/^(?:\])/,/^(?:\|)/,/^(?:<=)/,/^(?:<)/,/^(?:>=)/,/^(?:>)/,/^(?:!=)/,/^(?:==)/,/^(?:=)/,/^(?:-?[0-9]+(\.[0-9]+)?\b)/,/^(?:[a-zA-Z_][a-zA-Z0-9_]*)/,/^(?:'[^']*')/,/^(?:"[^"]*")/,/^(?:\.)/,/^(?:.)/,/^(?:$)/],conditions:{INITIAL:{rules:[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27],inclusive:!0}}}}();
I.lexer=fc;b.prototype=I;I.Parser=b;return new b}();function Zb(a){var b=this;this.ampdoc=a;Tb(a,function(){});var c=a.getElementById("amp-access");if(this.U=!!c)this.F=c,this.Sa=L(sa(a.win.location)).origin,this.B=W(a.win),this.P=V(a.win,"vsync"),this.Ya=ya(U(a),"cid"),this.o=X(a),this.nb=wa(a,"viewport"),this.lb=V(a.win,"templates"),this.jb=wa(a,"resources"),this.ma=va(a.win),this.ya=null,this.j=$b(this),c=this.j.map(function(a){return a.whenFirstAuthorized()}),this.ga=!1,this.N=Promise.all(c),this.$=null,this.Ja=new Sb,this.N.then(function(){b.ga=
!0;b.D("access-authorization-received");b.ma&&(b.ma.tick("aaa"),b.ma.tickSinceVisible("aaav"),b.ma.flush())}),a.getRootNode().addEventListener("amp:dom-update",this.gb.bind(this))}h=Zb.prototype;h.getAccessReaderId=function(){return this.U?this.ha():null};h.ha=function(){if(!this.ya){var a=Promise.resolve();this.ya=this.Ya.then(function(b){return b.get({scope:"amp-access",createCookieIfNotPresent:!0},a)})}return this.ya};h.areFirstAuthorizationsCompleted=function(){return this.ga};
h.onApplyAuthorizations=function(a){this.Ja.add(a)};
function $b(a){B(Ea(a.F),'amp-access config should be inside a <script> tag with type="application/json"');var b=Ka(a.F.textContent,function(a){throw x().createError('Failed to parse "amp-access" JSON: '+a);}),c={};if(Array.isArray(b))for(var d=b,e=0;e<d.length;e++){var f=d[e].namespace;B(!!f,"Namespace required");B(!c[f],"Namespace already used: "+f);c[f]=d[e]}else c[b.namespace||""]=b;var g=a.ha.bind(a),k=a.oa.bind(a),l=a.xa.bind(a);return Object.keys(c).map(function(b){return new Mb(a.ampdoc,c[b],
g,k,l,a.F)})}h.gb=function(a){var b=this;if(this.ga){var c=a.target;return this.N.then(function(){var a=b.combinedResponses();ac(b,c,a)})}};h.getVendorSource=function(a){for(var b=0;b<this.j.length;b++){var c=this.j[b];if("vendor"==c.getType()){var d=c.getAdapter();if(d.getVendorName()==a)return c}}B(!1,'Access vendor "%s" can only be used for "type=vendor", but none found',a);throw Error();};h.isEnabled=function(){return this.U};
h.ia=function(){var a=this.ampdoc.getRootNode();return a.documentElement||a.body||a};h.D=function(a){Kb(this.ia(),a)};function bc(a){a.o.onBroadcast(function(b){"amp-access-reauthorize"==b.type&&b.origin==a.Sa&&cc(a)})}h.xa=function(a){var b=this;this.Ma();a.then(function(){b.ga&&b.N.then(function(){b.ampdoc.whenReady().then(function(){var a=b.ampdoc.getRootNode(),d=b.combinedResponses();return ac(b,a,d)})})})};h.Ma=function(){this.o.broadcast(F({type:"amp-access-reauthorize",origin:this.Sa}))};
function cc(a){dc(a,"amp-access-loading",!0);var b=a.o.whenFirstVisible().then(function(){return Promise.all(a.j.map(function(b){return ec(a,b)}))}),c=b.then(function(){dc(a,"amp-access-loading",!1);return a.ampdoc.whenReady().then(function(){var b=a.ampdoc.getRootNode(),c=a.combinedResponses();return ac(a,b,c)})});a.N=c}function ec(a,b){return b.runAuthorization().catch(function(){dc(a,"amp-access-error",!0)})}
h.getAuthdataField=function(a){var b=this;return this.U?this.N.then(function(){var c=b.combinedResponses();c=Ja(c,a);return void 0!==c?c:null}):null};function ac(a,b,c){b=b.querySelectorAll("[amp-access]");for(var d=[],e=0;e<b.length;e++)d.push(gc(a,b[e],c));return Promise.all(d).then(function(){a.Ja.fire()})}
function gc(a,b,c){var d=b.getAttribute("amp-access");a:{try{Yb.yy=c;var e=!!Yb.parse(d);break a}finally{Yb.yy=null}e=void 0}var f=e,g=null;f&&(g=hc(a,b,c));return g?g.then(function(){return ic(a,b,f)}):ic(a,b,f)}function ic(a,b,c){var d=!b.hasAttribute("amp-access-hide");return c==d?Promise.resolve():a.jb.mutateElement(b,function(){c?b.removeAttribute("amp-access-hide"):b.setAttribute("amp-access-hide","")})}
function hc(a,b,c){var d=[],e=b.querySelectorAll("[amp-access-template]");if(0<e.length)for(var f={J:0};f.J<e.length;f={J:f.J},f.J++){var g=jc(a,e[f.J],c).catch(function(a){return function(c){z().error("amp-access","Template failed: ",c,e[a.J],b)}}(f));d.push(g)}return 0<d.length?Promise.all(d):null}
function jc(a,b,c){var d=b,e=null;"TEMPLATE"!=d.tagName&&(e=d,d=e.__AMP_ACCESS__TEMPLATE);return d?a.lb.renderTemplate(d,c).then(function(b){return a.P.mutatePromise(function(){b.setAttribute("amp-access-template","");b.__AMP_ACCESS__TEMPLATE=d;d.parentElement?d.parentElement.replaceChild(b,d):e&&e.parentElement&&e.parentElement.replaceChild(b,e)})}):Promise.reject(Error("template not found"))}
h.oa=function(a){var b=this;this.j.some(function(a){return a.getAdapter().isPingbackEnabled()})&&(this.$=null,this.ampdoc.whenReady().then(function(){b.o.isVisible()&&kc(b,a);b.o.onVisibilityChanged(function(){b.o.isVisible()&&kc(b,a)})}))};
function kc(a,b){a.$||(a.$=lc(a,b).then(function(){return a.N}).then(function(){a.D("access-viewed");for(var b=[],d=0;d<a.j.length;d++)a.j[d].getAdapter().isPingbackEnabled()&&b.push(a.j[d].reportViewToServer());return Promise.all(b)}).catch(function(b){a.$=null;throw b;}),a.$.then(a.Ma.bind(a)))}
function lc(a,b){if(0==b)return Promise.resolve();var c=[];return(new Promise(function(d,e){c.push(a.o.onVisibilityChanged(function(){a.o.isVisible()||e(Error("CANCELLED"))}));var f=a.B.delay(d,b);c.push(function(){return a.B.cancel(f)});c.push(a.nb.onScroll(d));c.push(yb(a.ampdoc.getRootNode(),d))})).then(function(){c.forEach(function(a){return a()})},function(a){c.forEach(function(a){return a()});throw a;})}function dc(a,b,c){a.P.mutate(function(){a.ia().classList.toggle(b,c)})}
h.bb=function(a){if(!a.satisfiesTrust(100))return null;if("login"==a.method)a.event&&a.event.preventDefault(),mc(this,"");else{var b=a.method;(6>b.length?0:0==b.lastIndexOf("login-",0))?(a.event&&a.event.preventDefault(),mc(this,a.method.substring(6))):"refresh"==a.method&&(a.event&&a.event.preventDefault(),cc(this))}return null};h.getSource=function(a){B(0<=a&&a<this.j.length,"Invalid index: %d",a);return this.j[a]};
function mc(a,b){var c=b.indexOf("-"),d=1==a.j.length,e=-1<c?b.substring(0,c):b,f=a.j.filter(function(a){return a.getNamespace()==e});if(f.length){var g=-1<c?b.substring(c+1):"";f[0].loginWithType(g)}else B(d,"Login must match namespace: %s",e),a.j[0].loginWithType(b)}h.combinedResponses=function(){if(1==this.j.length&&!this.j[0].getNamespace())return this.j[0].getAuthResponse()||{};var a={};this.j.forEach(function(b){return a[b.getNamespace()]=b.getAuthResponse()});return a};
(function(a){a.registerServiceForDoc("access",function(a){a=new Zb(a);if(a.U){ua(a.F,"action").installActionHandler(a.F,a.bb.bind(a));for(var b=0;b<a.j.length;b++)a.j[b].start();cc(a);a.oa(2E3);bc(a)}else x().info("amp-access",'Access is disabled - no "id=amp-access" element');return a})})(self.AMP);
})});

//# sourceMappingURL=amp-access-0.1.js.map
