(self.AMP=self.AMP||[]).push({n:"amp-audio",v:"1908231648370",f:(function(AMP,_){
var l,n="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},p;if("function"==typeof Object.setPrototypeOf)p=Object.setPrototypeOf;else{var q;a:{var r={a:!0},t={};try{t.__proto__=r;q=t.a;break a}catch(a){}q=!1}p=q?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var u=p;function v(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return b}};var w=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;var x=Object.prototype.toString;self.log=self.log||{user:null,dev:null,userForEmbed:null};var y=self.log;function z(){if(!y.user)throw Error("failed to call initLogConstructor");return y.user}function A(){if(y.dev)return y.dev;throw Error("failed to call initLogConstructor");}function B(a,b,d,e,c){z().assert(a,b,d,e,c,void 0,void 0,void 0,void 0,void 0,void 0)};function C(){var a=100;this.w=a;this.l=this.m=0;this.j=Object.create(null)}C.prototype.has=function(a){return!!this.j[a]};C.prototype.get=function(a){var b=this.j[a];if(b)return b.access=++this.l,b.payload};C.prototype.put=function(a,b){this.has(a)||this.m++;this.j[a]={payload:b,access:this.l};if(!(this.m<=this.w)){A().warn("lru-cache","Trimming LRU cache");a=this.j;var d=this.l+1,e;for(e in a){var c=a[e].access;if(c<d){d=c;var f=e}}void 0!==f&&(delete a[f],this.m--)}};(function(a){return a||{}})({c:!0,v:!0,a:!0,ad:!0,action:!0});var D,E;
function F(a,b){var d=void 0===d?"source":d;B(null!=a,"%s %s must be available",b,d);var e=a;a=e;if("string"==typeof a){D||(D=self.document.createElement("a"),E=self.UrlCache||(self.UrlCache=new C));var c=E,f=D;if(c&&c.has(a))a=c.get(a);else{f.href=a;f.protocol||(f.href=f.href);var g={href:f.href,protocol:f.protocol,host:f.host,hostname:f.hostname,port:"0"==f.port?"":f.port,pathname:f.pathname,search:f.search,hash:f.hash,origin:null};"/"!==g.pathname[0]&&(g.pathname="/"+g.pathname);if("http:"==g.protocol&&
80==g.port||"https:"==g.protocol&&443==g.port)g.port="",g.host=g.hostname;g.origin=f.origin&&"null"!=f.origin?f.origin:"data:"!=g.protocol&&g.host?g.protocol+"//"+g.host:g.href;c&&c.put(a,g);a=g}}(c="https:"==a.protocol||"localhost"==a.hostname||"127.0.0.1"==a.hostname)||(a=a.hostname,c=a.length-10,c=0<=c&&a.indexOf(".localhost",c)==c);B(c||/^(\/\/)/.test(e),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,d,e)};function G(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(c){A().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var d=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var e=0;e<d.length;e++)0!=d[e].length&&("-"==d[e][0]?a[d[e].substr(1)]=!1:a[d[e]]=!0);return a};function H(a){var b=a.ownerDocument.defaultView,d=b.__AMP_TOP||(b.__AMP_TOP=b),e=b!=d;var c=d;if(c.__AMP__EXPERIMENT_TOGGLES)var f=c.__AMP__EXPERIMENT_TOGGLES;else{c.__AMP__EXPERIMENT_TOGGLES=Object.create(null);f=c.__AMP__EXPERIMENT_TOGGLES;if(c.AMP_CONFIG)for(var g in c.AMP_CONFIG){var h=c.AMP_CONFIG[g];"number"===typeof h&&0<=h&&1>=h&&(f[g]=Math.random()<h)}if(c.AMP_CONFIG&&Array.isArray(c.AMP_CONFIG["allow-doc-opt-in"])&&0<c.AMP_CONFIG["allow-doc-opt-in"].length&&(g=c.AMP_CONFIG["allow-doc-opt-in"],
h=c.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){h=h.getAttribute("content").split(",");for(var m=0;m<h.length;m++)-1!=g.indexOf(h[m])&&(f[h[m]]=!0)}Object.assign(f,G(c));if(c.AMP_CONFIG&&Array.isArray(c.AMP_CONFIG["allow-url-opt-in"])&&0<c.AMP_CONFIG["allow-url-opt-in"].length){g=c.AMP_CONFIG["allow-url-opt-in"];h=c.location.originalHash||c.location.hash;c=Object.create(null);if(h)for(var k;k=w.exec(h);)m=v(k[1],k[1]),k=k[2]?v(k[2],k[2]):"",c[m]=k;for(h=0;h<g.length;h++)m=
c["e-"+g[h]],"1"==m&&(f[g[h]]=!0),"0"==m&&(f[g[h]]=!1)}}var S=!!f["ampdoc-fie"];e&&!S?a=I(b,"url")?J(b,"url"):null:(a=K(a),a=K(a),a=a.isSingleDoc()?a.win:a,a=I(a,"url")?J(a,"url"):null);return a}function K(a){if(a.nodeType){var b=(a.ownerDocument||a).defaultView;b=b.__AMP_TOP||(b.__AMP_TOP=b);a=J(b,"ampdoc").getAmpDoc(a)}return a}
function J(a,b){I(a,b);var d=a.services;d||(d=a.services={});var e=d;a=e[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function I(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function L(a,b){for(var d;a&&a!==d;a=a.parentElement)if(b(a))return a;return null}function M(a){return a.closest?a.closest("AMP-STORY"):L(a,function(a){var b=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return b?b.call(a,"AMP-STORY"):!1})};var N={title:"",artist:"",album:"",artwork:[{src:""}]};function O(a,b,d,e,c){var f=b.navigator;"mediaSession"in f&&b.MediaMetadata&&(f.mediaSession.metadata=new b.MediaMetadata(N),P(a,d),f.mediaSession.metadata=new b.MediaMetadata(d),f.mediaSession.setActionHandler("play",e),f.mediaSession.setActionHandler("pause",c))}
function Q(a){var b=a.querySelector('script[type="application/ld+json"]');if(b){try{var d=JSON.parse(b.textContent)}catch(c){d=null}var e=d;if(e&&e.image){if("string"===typeof e.image)return e.image;if(e.image["@list"]&&"string"===typeof e.image["@list"][0])return e.image["@list"][0];if("string"===typeof e.image.url)return e.image.url;if("string"===typeof e.image[0])return e.image[0]}}}
function P(a,b){var d=H(a);if(b&&b.artwork){var e=b.artwork;Array.isArray(e);e.forEach(function(a){a&&(a="[object Object]"===x.call(a)?a.src:a,B(d.isProtocolValid(a)))})}};var R;function T(a,b){var d=void 0,e=a,c=b;var f=function(a){try{return c(a)}catch(k){throw self.reportError(k),k;}};var g=U(),h=!1;d&&(h=d.capture);e.addEventListener("playing",f,g?d:h)}function U(){if(void 0!==R)return R;R=!1;try{var a={get capture(){R=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return R};function aa(a,b){T(a,b)};function V(a){a=AMP.BaseElement.call(this,a)||this;a.h=null;a.o=N;a.isPlaying=!1;return a}var W=AMP.BaseElement;V.prototype=n(W.prototype);V.prototype.constructor=V;if(u)u(V,W);else for(var X in W)if("prototype"!=X)if(Object.defineProperties){var Y=Object.getOwnPropertyDescriptor(W,X);Y&&Object.defineProperty(V,X,Y)}else V[X]=W[X];V.C=W.prototype;l=V.prototype;l.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a};
l.buildCallback=function(){"nodisplay"===this.getLayout()&&(this.element.removeAttribute("autoplay"),this.buildAudioElement());this.registerAction("play",this.B.bind(this));this.registerAction("pause",this.A.bind(this))};
l.buildAudioElement=function(){var a=this,b=this.element.ownerDocument.createElement("audio");if(!b.play)return this.toggleFallback(!0),Promise.resolve();b.controls=!0;var d=this.element.getAttribute("src");d&&F(d,this.element);this.propagateAttributes("src preload autoplay muted loop aria-label aria-describedby aria-labelledby controlsList".split(" "),b);this.applyFillContent(b);this.getRealChildNodes().forEach(function(a){a.getAttribute&&a.getAttribute("src")&&F(a.getAttribute("src"),a);b.appendChild(a)});
this.element.appendChild(b);this.h=b;aa(this.h,function(){return ba(a)})};
l.layoutCallback=function(){"nodisplay"!==this.getLayout()&&this.buildAudioElement();var a=this.getAmpDoc().win.document,b=this.element.getAttribute("artist")||"",d=this.element.getAttribute("title")||this.element.getAttribute("aria-label")||a.title||"",e=this.element.getAttribute("album")||"",c;(c=this.element.getAttribute("artwork")||Q(a))||(c=(c=a.querySelector('meta[property="og:image"]'))?c.getAttribute("content"):void 0);c||(c=(a=a.querySelector('link[rel="shortcut icon"]')||a.querySelector('link[rel="icon"]'))?
a.getAttribute("href"):void 0);this.o={title:d,artist:b,album:e,artwork:[{src:c||""}]};return"none"===this.element.getAttribute("preload")?this.h:this.loadPromise(this.h)};l.renderOutsideViewport=function(){return!0};l.pauseCallback=function(){this.h&&this.h.pause()};function Z(a){return a.h?M(a.element)?(z().warn("amp-audio","<amp-story> elements do not support actions on <amp-audio> elements"),!1):!0:!1}l.A=function(){Z(this)&&this.h.pause()};l.B=function(){Z(this)&&this.h.play()};
function ba(a){O(a.element,a.win,a.o,function(){a.h.play()},function(){a.h.pause()})}(function(a){a.registerElement("amp-audio",V)})(self.AMP);
})});

//# sourceMappingURL=amp-audio-0.1.js.map
