(self.AMP=self.AMP||[]).push({n:"amp-user-notification",v:"1908231648370",f:(function(AMP,_){
var m,n="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},p;if("function"==typeof Object.setPrototypeOf)p=Object.setPrototypeOf;else{var q;a:{var r={a:!0},t={};try{t.__proto__=r;q=t.a;break a}catch(a){}q=!1}p=q?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var u=p;function v(){var a,b;this.promise=new Promise(function(d,g){a=d;b=g});this.resolve=a;this.reject=b};function w(){this.h=0;this.R=Promise.resolve();this.O=function(){};this.P=function(){}}w.prototype.onQueueEmpty=function(a){this.O=a;0==this.h&&a()};w.prototype.onQueueNotEmpty=function(a){this.P=a;0<this.h&&a()};w.prototype.registerUI=function(a){var b=this;0==this.h&&this.P();this.h++;var d=this.R.then(function(){return a().then(function(){b.h--;0==b.h&&b.O()})});return this.R=d};function x(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return b}};var y=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function z(a){for(var b=null,d="",g=0;g<arguments.length;g++){var c=arguments[g];if(c instanceof Error&&!b){b=void 0;var e=Object.getOwnPropertyDescriptor(c,"message");if(e&&e.writable)b=c;else{e=c.stack;var f=Error(c.message);for(b in c)f[b]=c[b];f.stack=e;b=f}}else d&&(d+=" "),d+=c}b?d&&(b.message=d+": "+b.message):b=Error(d);return b}function A(a){var b=z.apply(null,arguments);setTimeout(function(){self.reportError(b);throw b;})}self.log=self.log||{user:null,dev:null,userForEmbed:null};var B=self.log;
function C(){if(!B.user)throw Error("failed to call initLogConstructor");return B.user}function D(){if(B.dev)return B.dev;throw Error("failed to call initLogConstructor");}function E(a,b,d,g,c){return C().assert(a,b,d,g,c,void 0,void 0,void 0,void 0,void 0,void 0)};function F(a){return a||{}};function G(){var a=100;this.U=a;this.C=this.G=0;this.o=Object.create(null)}G.prototype.has=function(a){return!!this.o[a]};G.prototype.get=function(a){var b=this.o[a];if(b)return b.access=++this.C,b.payload};G.prototype.put=function(a,b){this.has(a)||this.G++;this.o[a]={payload:b,access:this.C};if(!(this.G<=this.U)){D().warn("lru-cache","Trimming LRU cache");a=this.o;var d=this.C+1,g;for(g in a){var c=a[g].access;if(c<d){d=c;var e=g}}void 0!==e&&(delete a[e],this.G--)}};F({c:!0,v:!0,a:!0,ad:!0,action:!0});var H,I;
function J(a,b){var d=void 0===d?"source":d;E(null!=a,"%s %s must be available",b,d);var g=a;a=g;if("string"==typeof a){H||(H=self.document.createElement("a"),I=self.UrlCache||(self.UrlCache=new G));var c=I,e=H;if(c&&c.has(a))a=c.get(a);else{e.href=a;e.protocol||(e.href=e.href);var f={href:e.href,protocol:e.protocol,host:e.host,hostname:e.hostname,port:"0"==e.port?"":e.port,pathname:e.pathname,search:e.search,hash:e.hash,origin:null};"/"!==f.pathname[0]&&(f.pathname="/"+f.pathname);if("http:"==f.protocol&&
80==f.port||"https:"==f.protocol&&443==f.port)f.port="",f.host=f.hostname;f.origin=e.origin&&"null"!=e.origin?e.origin:"data:"!=f.protocol&&f.host?f.protocol+"//"+f.host:f.href;c&&c.put(a,f);a=f}}(c="https:"==a.protocol||"localhost"==a.hostname||"127.0.0.1"==a.hostname)||(a=a.hostname,c=a.length-10,c=0<=c&&a.indexOf(".localhost",c)==c);E(c||/^(\/\/)/.test(g),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,d,g)};function K(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(c){D().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var d=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var g=0;g<d.length;g++)0!=d[g].length&&("-"==d[g][0]?a[d[g].substr(1)]=!1:a[d[g]]=!0);return a};function aa(a){var b=a.ownerDocument.defaultView,d=b.__AMP_TOP||(b.__AMP_TOP=b),g=b!=d;var c=d;if(c.__AMP__EXPERIMENT_TOGGLES)var e=c.__AMP__EXPERIMENT_TOGGLES;else{c.__AMP__EXPERIMENT_TOGGLES=Object.create(null);e=c.__AMP__EXPERIMENT_TOGGLES;if(c.AMP_CONFIG)for(var f in c.AMP_CONFIG){var h=c.AMP_CONFIG[f];"number"===typeof h&&0<=h&&1>=h&&(e[f]=Math.random()<h)}if(c.AMP_CONFIG&&Array.isArray(c.AMP_CONFIG["allow-doc-opt-in"])&&0<c.AMP_CONFIG["allow-doc-opt-in"].length&&(f=c.AMP_CONFIG["allow-doc-opt-in"],
h=c.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){h=h.getAttribute("content").split(",");for(var l=0;l<h.length;l++)-1!=f.indexOf(h[l])&&(e[h[l]]=!0)}Object.assign(e,K(c));if(c.AMP_CONFIG&&Array.isArray(c.AMP_CONFIG["allow-url-opt-in"])&&0<c.AMP_CONFIG["allow-url-opt-in"].length){f=c.AMP_CONFIG["allow-url-opt-in"];h=c.location.originalHash||c.location.hash;c=Object.create(null);if(h)for(var k;k=y.exec(h);)l=x(k[1],k[1]),k=k[2]?x(k[2],k[2]):"",c[l]=k;for(h=0;h<f.length;h++)l=
c["e-"+f[h]],"1"==l&&(e[f[h]]=!0),"0"==l&&(e[f[h]]=!1)}}var ba=!!e["ampdoc-fie"];g&&!ba?a=L(b,"url-replace")?M(b,"url-replace"):null:(a=N(a),a=O(a),a=L(a,"url-replace")?M(a,"url-replace"):null);return a}function P(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return M(a,b)}function N(a){return a.nodeType?P((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function O(a){a=N(a);return a.isSingleDoc()?a.win:a}
function M(a,b){L(a,b);var d=Q(a);a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function R(a,b){var d=S(a,b);if(d)return d;a=Q(a);a[b]=ca();return a[b].promise}function S(a,b){var d=Q(a)[b];if(d){if(d.promise)return d.promise;M(a,b);return d.promise=Promise.resolve(d.obj)}return null}function Q(a){var b=a.services;b||(b=a.services={});return b}function L(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)}
function ca(){var a=new v,b=a,d=b.promise,g=b.resolve;b=b.reject;d.catch(function(){});return{obj:null,promise:d,resolve:g,reject:b,context:null,ctor:null}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function da(a){var b=S(O(a),"geo");if(b)return b;var d=N(a);return d.waitForBodyOpen().then(function(){var a=d.win;var b=d.win.document.head;if(b){var e=[];b=b.querySelectorAll("script[custom-element]");for(var f=0;f<b.length;f++)e.push(b[f].getAttribute("custom-element"))}else e=[];a=e.includes("amp-geo")?P(a,"extensions").waitForExtension(a,"amp-geo"):Promise.resolve();return a}).then(function(){return S(O(a),"geo")})};function T(a){a=AMP.BaseElement.call(this,a)||this;a.J=null;a.m=null;var b=new v;a.K=b.promise;a.L=b.resolve;a.l=null;a.F=!1;a.A=null;a.B=null;a.w=null;a.j=null;a.H="";a.I=null;a.T=null;return a}var U=AMP.BaseElement;T.prototype=n(U.prototype);T.prototype.constructor=T;if(u)u(T,U);else for(var V in U)if("prototype"!=V)if(Object.defineProperties){var W=Object.getOwnPropertyDescriptor(U,V);W&&Object.defineProperty(T,V,W)}else T[V]=U[V];T.Z=U.prototype;m=T.prototype;m.isAlwaysFixed=function(){return!0};
m.buildCallback=function(){var a=this,b=this.getAmpDoc();this.T=aa(this.element);this.I=R(O(this.element),"storage");this.m=E(this.element.id,"amp-user-notification should have an id.");this.H="amp-user-notification:"+this.m;this.A=this.element.getAttribute("data-show-if-geo");this.B=this.element.getAttribute("data-show-if-not-geo");(this.j=this.element.getAttribute("data-show-if-href"))&&J(this.j,this.element);E(1>=!!this.j+!!this.A+!!this.B,'Only one "data-show-if-*" attribute allowed');this.A&&
(this.w=X(this,this.A,!0));this.B&&(this.w=X(this,this.B,!1));(this.l=this.element.getAttribute("data-dismiss-href"))&&J(this.l,this.element);var d=this.element.getAttribute("role");d||this.element.setAttribute("role","alert");var g=this.element.getAttribute("data-persist-dismissal");this.F="false"!=g&&"no"!=g;this.registerDefaultAction(function(){return a.dismiss(!1)},"dismiss");this.registerAction("optoutOfCid",function(){return ea(a)});var c=R(O(b),"userNotificationManager");c.then(function(b){b.registerUserNotification(a.m,
a)})};function X(a,b,d){return da(a.element).then(function(a){E(a,"requires <amp-geo> to use promptIfUnknownForGeoGroup");var c=b.split(/,\s*/).filter(function(b){return 2==a.isInCountryGroup(b)});return!(d?!c.length:c.length)})}
function fa(a,b){var d=a.j;return a.T.expandUrlAsync(d).then(function(d){var c={elementId:a.m,ampUserId:b};var e=[];for(k in c){var f=c[k];if(null!=f)if(Array.isArray(f))for(var g=0;g<f.length;g++){var l=f[g];e.push(encodeURIComponent(k)+"="+encodeURIComponent(l))}else e.push(encodeURIComponent(k)+"="+encodeURIComponent(f))}c=e.join("&");e=d;if(c){e=e.split("#",2);var k=e[0].split("?",2);c=k[0]+(k[1]?"?"+k[1]+"&"+c:"?"+c);c+=e[1]?"#"+e[1]:""}else c=e;return c})}
m.V=function(a){var b=this;this.J=a;return fa(this,a).then(function(a){var d={credentials:"include"};return P(b.win,"xhr").fetchJson(a,d).then(function(a){return a.json()})})};function ha(a){var b=a.element.getAttribute("enctype")||"application/json;charset=utf-8";P(a.win,"xhr").fetchJson(a.l,{method:"POST",credentials:"include",body:F({elementId:a.m,ampUserId:a.J}),headers:{"Content-Type":b}})}
m.X=function(a){E("boolean"==typeof a.showNotification,'`showNotification` should be a boolean. Got "%s" which is of type %s.',a.showNotification,typeof a.showNotification);a.showNotification||this.L();return Promise.resolve(a.showNotification)};function ea(a){return R(O(a.element),"cid").then(function(a){return a.optOut()}).then(function(){return a.dismiss(!1)},function(b){D().error("amp-user-notification","Failed to opt out of Cid",b);a.dismiss(!0)})}
function ia(a){return R(O(a.element),"cid").then(function(b){return b.get({scope:"amp-user-notification",createCookieIfNotPresent:!0},Promise.resolve(),a.K)})}m.shouldShow=function(){var a=this;return this.isDismissed().then(function(b){return b?!1:a.j?ia(a).then(a.V.bind(a)).then(a.X.bind(a)):a.w?a.w:!0})};
m.show=function(){var a=this.element,b=!0;void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","");this.element.classList.add("amp-active");this.getViewport().addToFixedLayer(this.element);return this.K};m.isDismissed=function(){var a=this;return this.F?this.I.then(function(b){return b.get(a.H)}).then(function(a){return!!a},function(a){D().error("amp-user-notification","Failed to read storage",a);return!1}):Promise.resolve(!1)};
m.dismiss=function(a){var b=this;this.element.classList.remove("amp-active");this.element.classList.add("amp-hidden");this.L();this.getViewport().removeFromFixedLayer(this.element);this.F&&!a&&this.I.then(function(a){a.set(b.H,!0)});this.l&&ha(this)};
function Y(a){this.ampdoc=a;this.S=Object.create(null);this.D=Object.create(null);a=N(this.ampdoc);a=O(a);this.Y=M(a,"viewer");this.M=this.ampdoc.whenReady();this.N=Promise.all([this.Y.whenFirstVisible(),this.M]);this.W=R(O(this.ampdoc),"notificationUIManager")}Y.prototype.get=function(a){var b=this;this.N.then(function(){null==b.ampdoc.getElementById(a)&&C().warn("amp-user-notification","Did not find amp-user-notification element "+a+".")});return Z(this,a).promise};
Y.prototype.getNotification=function(a){var b=this;return this.M.then(function(){return b.S[a]})};Y.prototype.registerUserNotification=function(a,b){var d=this;this.S[a]=b;var g=Z(this,a);return this.N.then(function(){return b.shouldShow()}).then(function(a){if(a)return d.W.then(function(a){return a.registerUI(b.show.bind(b))})}).then(g.resolve.bind(this,b)).catch(A.bind(null,"Notification service failed amp-user-notification",a))};
function Z(a,b){if(a.D[b])return a.D[b];var d=new v;return a.D[b]={promise:d.promise,resolve:d.resolve}}(function(a){a.registerServiceForDoc("userNotificationManager",Y);a.registerServiceForDoc("notificationUIManager",w);a.registerElement("amp-user-notification",T,"amp-user-notification{position:fixed!important;bottom:0;left:0;overflow:hidden!important;visibility:hidden;background:hsla(0,0%,100%,0.7);z-index:1000;width:100%}amp-user-notification.amp-active{visibility:visible}amp-user-notification.amp-hidden{visibility:hidden}\n/*# sourceURL=/extensions/amp-user-notification/0.1/amp-user-notification.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-user-notification-0.1.js.map
