(self.AMP=self.AMP||[]).push({n:"amp-sidebar",v:"1908231648370",f:(function(AMP,_){
var aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},m;if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var p;a:{var ba={a:!0},q={};try{q.__proto__=ba;p=q.a;break a}catch(a){}p=!1}m=p?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var r=m;function t(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var ca=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function u(a){return a?Array.prototype.slice.call(a):[]};self.log=self.log||{user:null,dev:null,userForEmbed:null};var w=self.log;function x(){if(!w.user)throw Error("failed to call initLogConstructor");return w.user}function da(a,b){return x().assert(a,'"toolbar-target" is required',b,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function y(){var a,b=Object.create(null);a&&Object.assign(b,a);return b};function z(a){var b=a.indexOf("#");return-1==b?a:a.substring(0,b)};function ea(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(k){if(w.dev)a=w.dev;else throw Error("failed to call initLogConstructor");a.warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var d=0;d<c.length;d++)0!=c[d].length&&("-"==c[d][0]?a[c[d].substr(1)]=!1:a[c[d]]=!0);return a};function A(a,b){var c=a.ownerDocument.defaultView,d=c.__AMP_TOP||(c.__AMP_TOP=c),k=c!=d;var e=d;if(e.__AMP__EXPERIMENT_TOGGLES)var g=e.__AMP__EXPERIMENT_TOGGLES;else{e.__AMP__EXPERIMENT_TOGGLES=Object.create(null);g=e.__AMP__EXPERIMENT_TOGGLES;if(e.AMP_CONFIG)for(var h in e.AMP_CONFIG){var f=e.AMP_CONFIG[h];"number"===typeof f&&0<=f&&1>=f&&(g[h]=Math.random()<f)}if(e.AMP_CONFIG&&Array.isArray(e.AMP_CONFIG["allow-doc-opt-in"])&&0<e.AMP_CONFIG["allow-doc-opt-in"].length&&(h=e.AMP_CONFIG["allow-doc-opt-in"],
f=e.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){f=f.getAttribute("content").split(",");for(var l=0;l<f.length;l++)-1!=h.indexOf(f[l])&&(g[f[l]]=!0)}Object.assign(g,ea(e));if(e.AMP_CONFIG&&Array.isArray(e.AMP_CONFIG["allow-url-opt-in"])&&0<e.AMP_CONFIG["allow-url-opt-in"].length){h=e.AMP_CONFIG["allow-url-opt-in"];f=e.location.originalHash||e.location.hash;e=Object.create(null);if(f)for(var n;n=ca.exec(f);)l=t(n[1],n[1]),n=n[2]?t(n[2],n[2]):"",e[l]=n;for(f=0;f<h.length;f++)l=
e["e-"+h[f]],"1"==l&&(g[h[f]]=!0),"0"==l&&(g[h[f]]=!1)}}var v=!!g["ampdoc-fie"];k&&!v?b=B(c,b)?C(c,b):null:(a=D(a),a=E(a),b=B(a,b)?C(a,b):null);return b}function F(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return C(a,b)}function G(a,b){var c=D(a);c=E(c);return C(c,b)}function D(a){return a.nodeType?F((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function E(a){a=D(a);return a.isSingleDoc()?a.win:a}
function C(a,b){B(a,b);var c=a.services;c||(c=a.services={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function B(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var H;function I(a){return":not([toolbar]) [autoscroll]".replace(/^|,/g,"$&"+a+" ")};function J(a){var b=a.isConnected;if(void 0===b){do if(a=K(a),a.host)a=a.host;else break;while(1)}}function K(a){if(Node.prototype.getRootNode)return a.getRootNode()||a;for(;a.parentNode&&(!a||"I-AMPHTML-SHADOW-ROOT"!=a.tagName&&(11!=a.nodeType||"[object ShadowRoot]"!==Object.prototype.toString.call(a)));a=a.parentNode);return a}function fa(a,b){for(var c;a&&a!==c;a=a.parentElement)if(b(a))return a;return null}
function L(a,b){return a.closest?a.closest(b):fa(a,function(a){var c=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return c?c.call(a,b):!1})}function ha(a){var b=a.body.getAttribute("dir")||a.documentElement.getAttribute("dir")||"ltr";return"rtl"==b};var M,N="Webkit webkit Moz moz ms O o".split(" ");function O(a,b){void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function P(a,b){if(void 0!==H)var c=H;else{try{var d=b.ownerDocument,k=d.createElement("div"),e=d.createElement("div");k.appendChild(e);c=k.querySelector(":scope div")===e}catch(f){c=!1}c=H=c}c?c=b.querySelector(I(":scope")):(b.classList.add("i-amphtml-scoped"),c=I(".i-amphtml-scoped"),c=b.querySelectorAll(c),b.classList.remove("i-amphtml-scoped"),c=void 0===c[0]?null:c[0]);if(c){var g=(a.win.getComputedStyle(b)||y())["overflow-y"];if("scroll"!=g&&"auto"!=g)x().error("AMP-SIDEBAR","for 'autoscroll', 'nav [toolbar]' element must be set to overflow\n        'scroll' or 'auto' for 'autoscroll' to work.");
else{var h=G(a,"viewport");h.animateScrollWithinParent(c,b,"center",0)}}};function Q(a,b){this.M=b;this.c=a;this.F=b.getAmpDoc();this.U=this.c.getAttribute("toolbar");this.D=null;this.h=void 0;this.I=!1;this.c.classList.add("amp-sidebar-toolbar-target-hidden");ia(this)}Q.prototype.onLayoutChange=function(){var a=this.F.win.matchMedia(this.U).matches;a?ja(this):ka(this)};
function ia(a){a.D=a.c.cloneNode(!0);var b=da(a.c.getAttribute("toolbar-target"),a.c);a.F.whenReady().then(function(){var c=a.F.getElementById(b);if(c)a.h=c,a.D.classList.add("i-amphtml-toolbar"),O(a.h,!1);else throw Error("Could not find the toolbar-target element with an id: "+b);})}
function ja(a){a.I?Promise.resolve():a.M.mutateElement(function(){a.h&&(O(a.h,!0),a.h.contains(a.D)||a.h.appendChild(a.D),a.c.classList.add("amp-sidebar-toolbar-target-shown"),a.c.classList.remove("amp-sidebar-toolbar-target-hidden"),a.I=!0,P(a.F,a.D))})}function ka(a){a.I&&a.M.mutateElement(function(){a.h&&(O(a.h,!1),a.c.classList.add("amp-sidebar-toolbar-target-hidden"),a.c.classList.remove("amp-sidebar-toolbar-target-shown"),a.I=!1)})};var R=[];function la(a){var b=[];a=S(a);for(var c={},d=0;d<a.length;c={w:c.w},d++)c.w=a[d],c.w.parentNode&&u(c.w.parentNode.children).filter(function(a){return function(b){return b!=a.w}}(c)).forEach(function(a){return b.push(a)});return b}function S(a){for(var b=[],c=a;c;c=c.parentNode||c.host)b.push(c);return b}
function ma(a){for(var b=[];a;){a=K(a);var c=a.querySelectorAll("a[href],area[href],button,details summary,iframe,input,select,textarea,[contenteditable],[draggable],[tabindex]");Array.prototype.push.apply(b,c);a=a.host}return b}
function na(a){R.every(function(b){return b.element!==a});J(a);var b=la(a),c=S(a).filter(function(a){return a.nodeType==Node.ELEMENT_NODE}),d=ma(a),k=d.filter(function(b){return a.contains(b)&&void 0!==b.__AMP_MODAL_SAVED_TAB_INDEX}),e=d.filter(function(b){return!a.contains(b)&&void 0===b.__AMP_MODAL_SAVED_TAB_INDEX}),g=b.concat(c).map(function(a){return{element:a,prevValue:a.getAttribute("aria-hidden")}});c.forEach(function(a){return a.removeAttribute("aria-hidden")});b.forEach(function(a){return a.setAttribute("aria-hidden",
"true")});e.forEach(function(a){a.__AMP_MODAL_SAVED_TAB_INDEX=a.getAttribute("tabindex");a.setAttribute("tabindex","-1")});k.forEach(function(a){var b=a.__AMP_MODAL_SAVED_TAB_INDEX;null===b?a.removeAttribute("tabindex"):a.setAttribute("tabindex",b)});R.push({element:a,hiddenElementInfos:g,focusableExternalElements:e,focusableInternalElements:k})}
function oa(a){var b=R.pop(),c=b.hiddenElementInfos,d=b.focusableExternalElements;b=b.focusableInternalElements;J(a);c.forEach(function(a){var b=a.prevValue;a=a.element;var c=b;null===c?a.removeAttribute("aria-hidden"):a.setAttribute("aria-hidden",c)});b.forEach(function(a){a.setAttribute("tabindex","-1")});d.forEach(function(a){var b=a.__AMP_MODAL_SAVED_TAB_INDEX;null===b?a.removeAttribute("tabindex"):a.setAttribute("tabindex",b);a.__AMP_MODAL_SAVED_TAB_INDEX=void 0})};function T(a){a=AMP.BaseElement.call(this,a)||this;a.o=null;a.J=null;a.P=null;a.B=null;a.l=a.win.document;a.R=a.l.documentElement;a.C=null;a.O=[];var b=F(a.win,"platform");a.H=b.isIos();a.S=b.isSafari();a.G=-1;a.L=!1;a.A=null;a.K=null;a.N=0;a.m=!1;return a}var U=AMP.BaseElement;T.prototype=aa(U.prototype);T.prototype.constructor=T;if(r)r(T,U);else for(var V in U)if("prototype"!=V)if(Object.defineProperties){var W=Object.getOwnPropertyDescriptor(U,V);W&&Object.defineProperty(T,V,W)}else T[V]=U[V];
T.V=U.prototype;
T.prototype.buildCallback=function(){var a=this,b=this.element;b.classList.add("i-amphtml-overlay");b.classList.add("i-amphtml-scrollable");this.C=b.getAttribute("side");this.o=this.getViewport();this.J=A(b,"action");"left"!=this.C&&"right"!=this.C&&(this.C=pa(this,ha(this.l)?"right":"left"),b.setAttribute("side",this.C));var c=u(b.querySelectorAll("nav[toolbar]"));c.forEach(function(b){try{a.O.push(new Q(b,a))}catch(k){a.user().error("amp-sidebar toolbar","Failed to instantiate toolbar",k)}});this.H&&
qa(this);b.setAttribute("aria-hidden","true");b.hasAttribute("role")||b.setAttribute("role","menu");b.tabIndex=-1;this.R.addEventListener("keydown",function(b){"Escape"==b.key&&a.j()&&b.preventDefault()});this.A=ra(this);this.A||(this.A=this.createScreenReaderCloseButton(),b.insertBefore(this.A,this.element.firstChild));b.appendChild(this.createScreenReaderCloseButton());this.registerDefaultAction(function(b){return X(a,b)},"open");this.registerAction("toggle",this.T.bind(this));this.registerAction("close",
this.j.bind(this));b.addEventListener("click",function(c){if((c=L(c.target,"A"))&&c.href){var d=A(b,"url").parse(c.href),e=a.getAmpDoc().win.location.href;z(c.href)==z(e)&&d.hash&&a.j()}},!0)};function ra(a){for(var b=a.element.querySelectorAll("[on]"),c=0;c<b.length;c++){var d=b[c],k=a.J.hasResolvableActionForTarget(d,"tap",a.element,d.parentElement),e=L(d,"[toolbar]");if(k&&!e)return d}return null}
T.prototype.createScreenReaderCloseButton=function(){var a=this,b=this.element.getAttribute("data-close-button-aria-label")||"Close the sidebar",c=this.l.createElement("button");c.textContent=b;c.classList.add("i-amphtml-screen-reader");c.tabIndex=-1;c.addEventListener("click",function(){a.j()});return c};T.prototype.onLayoutMeasure=function(){var a=this;this.getAmpDoc().whenReady().then(function(){a.O.forEach(function(a){a.onLayoutChange()})})};T.prototype.T=function(a){this.m?this.j():X(this,a)};
function Y(a,b,c){function d(){a.P===b&&a.mutateElement(b)}a.P=b;c?F(a.win,"timer").delay(d,c):d()}
function sa(a){O(a.element,!0);a.o.addToFixedLayer(a.element,!0);a.mutateElement(function(){na(a.element)});a.H&&a.S&&ta(a);a.element.scrollTop=1;ua(a);a.element.setAttribute("open","");a.element.setAttribute("aria-hidden","false");Y(a,function(){var b=a.getRealChildren(),c=G(a.element,"owners");c.scheduleLayout(a.element,b);c.scheduleResume(a.element,b);if(!a.H||!G(a.element,"viewer").isEmbedded())try{a.A.focus()}catch(d){}Z(a,"sidebarOpen")},350);P(a.getAmpDoc(),a.element)}
function va(a){a.B&&a.B.classList.toggle("i-amphtml-ghost",!0);a.mutateElement(function(){oa(a.element)});a.element.removeAttribute("open");a.element.setAttribute("aria-hidden","true");Y(a,function(){O(a.element,!1);G(a.element,"owners").schedulePause(a.element,a.getRealChildren());Z(a,"sidebarClose")},350)}
function X(a,b){a.m||(a.m=!0,a.o.enterOverlayMode(),Y(a,function(){return sa(a)}),G(a.getAmpDoc(),"history").push(a.j.bind(a)).then(function(b){a.G=b}),b&&(a.K=b.caller,a.N=a.o.getScrollTop()))}
T.prototype.j=function(){var a=this;if(!this.m)return!1;this.m=!1;this.o.leaveOverlayMode();var b=this.N==this.o.getScrollTop(),c=this.element.contains(this.l.activeElement);Y(this,function(){return va(a)});-1!=this.G&&(G(this.getAmpDoc(),"history").pop(this.G),this.G=-1);if(this.K&&c&&b&&(!this.H||!G(this.element,"viewer").isEmbedded()))try{this.K.focus()}catch(d){}return!0};function pa(a,b){return L(a.element,"amp-story")?"left"==b?"right":"left":b}
function ua(a){if(!a.B){var b=a.l.createElement("div");b.classList.add("i-amphtml-sidebar-mask");b.addEventListener("click",function(){a.j()});a.getAmpDoc().getBody().appendChild(b);b.addEventListener("touchmove",function(a){a.preventDefault()});a.B=b}a.B.classList.toggle("i-amphtml-ghost",!1)}
function qa(a){a.element.addEventListener("scroll",function(b){a.m&&(1>a.element.scrollTop?(a.element.scrollTop=1,b.preventDefault()):a.element.scrollHeight==a.element.scrollTop+a.element.offsetHeight&&(--a.element.scrollTop,b.preventDefault()))})}
function ta(a){if(!a.L){var b=a.l.createElement("div"),c={height:"54px",width:"100%","background-color":"transparent"},d;for(d in c){var k=b,e=c[d];var g=k.style;var h=d;if(2>h.length?0:0==h.lastIndexOf("--",0))g=h;else{M||(M=y());var f=M[h];if(!f){f=h;if(void 0===g[h]){var l=h;l=l.charAt(0).toUpperCase()+l.slice(1);b:{for(var n=0;n<N.length;n++){var v=N[n]+l;if(void 0!==g[v]){l=v;break b}}l=""}void 0!==g[l]&&(f=l)}M[h]=f}g=f}g&&(k.style[g]=e)}a.element.appendChild(b);a.L=!0}}
function Z(a,b){var c=a.win;var d="amp-sidebar toolbar."+b;var k={};var e={detail:k};Object.assign(e,void 0);"function"==typeof c.CustomEvent?d=new c.CustomEvent(d,e):(c=c.document.createEvent("CustomEvent"),c.initCustomEvent(d,!!e.bubbles,!!e.cancelable,k),d=c);a.J.trigger(a.element,b,d,100)}(function(a){a.registerElement("amp-sidebar",T,"amp-sidebar{--story-page-vh:1vh;position:fixed!important;top:0;max-height:100vh!important;height:100vh;max-width:80vw;background-color:#efefef;min-width:45px!important;outline:none;overflow-x:hidden!important;overflow-y:auto!important;z-index:2147483647;-webkit-overflow-scrolling:touch;will-change:transform}amp-sidebar[side=left]{left:0!important;transform:translateX(-100%);animation-name:i-amphtml-sidebar-slide-out-left}amp-sidebar[side=left][open]{animation-name:i-amphtml-sidebar-slide-in-left}amp-sidebar[side=right]{right:0!important;transform:translateX(100%);animation-name:i-amphtml-sidebar-slide-out-right}amp-sidebar[side=right][open]{animation-name:i-amphtml-sidebar-slide-in-right}amp-sidebar[side]{animation-duration:233ms;animation-timing-function:cubic-bezier(0,0,.21,1);animation-fill-mode:forwards}.i-amphtml-toolbar>ol,.i-amphtml-toolbar>ul{display:-ms-flexbox;display:flex;-ms-flex-pack:start;justify-content:flex-start;-ms-flex-wrap:wrap;flex-wrap:wrap;overflow:auto;list-style-type:none;padding:0;margin:0}.i-amphtml-sidebar-mask{position:fixed!important;top:0!important;left:0!important;width:100vw!important;height:100vh!important;opacity:0.2;background-image:none!important;background-color:#000;z-index:2147483646}@keyframes i-amphtml-sidebar-slide-in-left{0%{transform:translateX(-100%)}to{transform:translateX(0)}}@keyframes i-amphtml-sidebar-slide-out-left{0%{transform:translateX(0)}to{transform:translateX(-100%)}}@keyframes i-amphtml-sidebar-slide-in-right{0%{transform:translateX(100%)}to{transform:translateX(0)}}@keyframes i-amphtml-sidebar-slide-out-right{0%{transform:translateX(0)}to{transform:translateX(100%)}}\n/*# sourceURL=/extensions/amp-sidebar/0.1/amp-sidebar.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-sidebar-0.1.js.map
